#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/youtu_vita/modular_youtu_vita.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_youtu_vita.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨


from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig
from ...modeling_rope_utils import RopeParameters
from ...utils import auto_docstring


class YoutuVITAAudioConfig(PreTrainedConfig):
    r"""
    YoutuVITAAudioConfig
    """

    model_type = "youtu_vita_audio"
    base_config_key = "audio_config"

    def __init__(
        self,
        hidden_size=512,
        attention_heads=4,
        linear_units=2048,
        num_blocks=50,
        tp_blocks=20,
        dropout_rate=0.0,
        positional_dropout_rate=0.0,
        attention_dropout_rate=0.0,
        normalize_before=True,
        kernel_size=11,
        sanm_shfit=0,
        input_size=560,
        temporal_merge_size=1,
        out_hidden_size=4608,
        merger_hidden_size=4608,
        # CNN
        num_mel_bins=128,
        downsample_hidden_size=512,
        n_window=50,
        n_window_infer=800,
        conv_chunksize=500,
        **kwargs,
    ):
        super().__init__(**kwargs)

        # SANM
        self.input_size = input_size
        self.attention_heads = attention_heads
        self.linear_units = linear_units
        self.num_blocks = num_blocks
        self.tp_blocks = tp_blocks
        self.dropout_rate = dropout_rate
        self.positional_dropout_rate = positional_dropout_rate
        self.attention_dropout_rate = attention_dropout_rate
        self.normalize_before = normalize_before
        self.kernel_size = kernel_size
        self.sanm_shfit = sanm_shfit

        self.hidden_size = hidden_size
        self.temporal_merge_size = temporal_merge_size
        self.out_hidden_size = out_hidden_size
        self.merger_hidden_size = merger_hidden_size

        # CNN
        self.downsample_hidden_size = downsample_hidden_size
        self.num_mel_bins = num_mel_bins
        self.n_window = n_window
        self.n_window_infer = n_window_infer
        self.conv_chunksize = conv_chunksize
        self.num_hidden_layers = 0


class YoutuVITAVisionConfig(PreTrainedConfig):
    r"""
    YoutuVITAVisionConfig
    """

    model_type = "youtu_vita_vision"
    base_config_key = "vision_config"

    vocab_size: int = 151936
    hidden_size: int = 4096
    intermediate_size: int = 22016
    num_hidden_layers: int = 32
    num_attention_heads: int = 32
    num_key_value_heads: int | None = 32
    head_dim: int = 128
    hidden_act: str = "silu"
    max_position_embeddings: int = 32768
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    tie_word_embeddings: bool = False
    rope_parameters: RopeParameters | dict | None = None
    attention_bias: bool = False
    use_sliding_window: bool = False
    sliding_window: int | None = 4096
    max_window_layers: int = 28
    layer_types: list[str] | None = None
    attention_dropout: float | int = 0.0
    pad_token_id: int | None = None
    bos_token_id: int | None = None
    eos_token_id: int | list[int] | None = None

    def __init__(
        self,
        hidden_size=768,
        intermediate_size=3072,
        num_hidden_layers=12,
        num_attention_heads=12,
        num_channels=3,
        num_patches=256,
        patch_size=16,
        hidden_act="gelu_pytorch_tanh",
        layer_norm_eps=1e-6,
        attention_dropout=0.0,
        spatial_merge_size=2,
        out_hidden_size=4608,
        merger_hidden_size=4608,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.num_channels = num_channels
        self.patch_size = patch_size
        self.attention_dropout = attention_dropout
        self.layer_norm_eps = layer_norm_eps
        self.hidden_act = hidden_act
        self.num_patches = num_patches
        self.spatial_merge_size = spatial_merge_size
        self.out_hidden_size = out_hidden_size
        self.merger_hidden_size = merger_hidden_size

    def __post_init__(self, **kwargs):
        self.sliding_window = self.sliding_window if self.use_sliding_window else None
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads

        if self.layer_types is None:
            self.layer_types = [
                "sliding_attention"
                if self.sliding_window is not None and i >= self.max_window_layers
                else "full_attention"
                for i in range(self.num_hidden_layers)
            ]
        super().__post_init__(**kwargs)


@auto_docstring(checkpoint="tencent/YoutuVITAText-LLM-2B")
@strict
class YoutuVITATextConfig(PreTrainedConfig):
    r"""
    YoutuVITATextConfig
    """

    model_type = "youtu_vita_text"
    keys_to_ignore_at_inference = ["past_key_values"]
    base_model_tp_plan = {
        "layers.*.mlp.gate_proj": "colwise",
        "layers.*.mlp.up_proj": "colwise",
        "layers.*.mlp.down_proj": "rowwise",
    }
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]),
        "layers": (["hidden_states", "attention_mask"], ["hidden_states"]),
        "norm": (["hidden_states"], ["hidden_states"]),
    }
    attribute_map = {}

    vocab_size: int = 128256
    hidden_size: int = 2048
    intermediate_size: int = 6144
    num_hidden_layers: int = 32
    num_attention_heads: int = 16
    num_key_value_heads: int = 16
    kv_lora_rank: int = 512
    q_lora_rank: int | None = 1536
    qk_rope_head_dim: int = 64
    v_head_dim: int | None = 128
    qk_nope_head_dim: int = 128
    hidden_act: str = "silu"
    max_position_embeddings: int = 131072
    initializer_range: float | None = None
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 128000
    eos_token_id: int | list[int] | None = 128001
    tie_word_embeddings: bool = True
    rope_parameters: RopeParameters | dict | None = None
    rope_interleave: bool | None = True
    attention_bias: bool = False
    attention_dropout: float | int | None = 0.0
    embedding_initializer_range: float | None = None
    base_config_key = "text_config"

    def __post_init__(self, **kwargs):
        if self.initializer_range is None:
            if self.hidden_size != 0:
                self.initializer_range = 2.0 / (5.0 * self.hidden_size) ** 0.5
            else:
                self.initializer_range = 0.02

        self.embedding_initializer_range = self.embedding_initializer_range or 2.0 * self.initializer_range
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads

        self.qk_head_dim = self.qk_nope_head_dim + self.qk_rope_head_dim
        self.head_dim = self.qk_rope_head_dim
        super().__post_init__(**kwargs)


class YoutuVITAOmniConfig(YoutuVITATextConfig):
    model_type = "youtu_vita_omni"
    base_config_key = "omni_config"

    # ---- Omni-specific fields ------------------------------------------------
    # Vision front-end
    num_channels: int = 3
    patch_size: int = 16
    spatial_merge_size: int = 2
    # Audio Conv2d front-end (mirrors :class:`YoutuVITACNNAudioEmbeddings`)
    num_mel_bins: int = 128
    downsample_hidden_size: int = 512
    n_window: int = 50
    n_window_infer: int = 800
    conv_chunksize: int = 500
    temporal_merge_size: int = 2
    # Projection to LM hidden size
    merger_hidden_size: int = 4608
    out_hidden_size: int = 4608
    # If True, each video is further split into ``(I+ A*)`` groups inside the
    # joint encoder, so attention is restricted to images / audios that belong
    # to the same group. See :meth:`YoutuVITAOmniModel.forward_video`.
    video_group_attention: bool = False
    # Per-omni-encoder-layer mask controlling which layers apply video fusion
    # attention. Mirrors the megatron-side ``--video-fusion-layer-freq`` arg.
    # Accepted values:
    #   * ``None`` (default) -- every layer is a fusion layer (legacy
    #     behaviour: image + audio of the same video share an attention
    #     window inside every layer).
    #   * ``int N`` -- moe-style 1:N ratio, layer ``i`` is fusion iff
    #     ``i % N == 0``.
    #   * ``list[int]`` of length ``num_hidden_layers`` -- explicit 0/1
    #     mask. ``1`` = fusion layer (segmentation follows
    #     ``video_group_attention``); ``0`` = non-fusion layer (each image
    #     and each audio chunk is its own attention window).
    # Only used by :meth:`YoutuVITAOmniModel.forward_video`; non-video
    # paths already encode each image / audio independently.
    video_fusion_layer_freq: int | list | None = None


class YoutuVITAConfig(PreTrainedConfig):
    r"""
    YoutuVITAConfig
    """

    model_type = "youtu_vita"
    sub_configs = {
        "audio_config": YoutuVITAAudioConfig,
        "vision_config": YoutuVITAVisionConfig,
        "text_config": YoutuVITATextConfig,
        "omni_config": YoutuVITAOmniConfig,
    }
    keys_to_ignore_at_inference = ["past_key_values"]

    def __init__(
        self,
        audio_config=None,
        text_config=None,
        vision_config=None,
        omni_config=None,
        # image_token_id=133375,
        # video_token_id=133379,
        # audio_token_id=133383,
        # image_pad_token_id=133376,
        # audio_pad_token_id=133384,
        # vision_start_token_id=133377,
        # vision_end_token_id=133378,
        tie_word_embeddings=False,
        # When True, the omni model runs the joint cross-modal
        # ``forward_video`` over the dedicated ``video_*`` buffers
        # produced by the video processor (vision frames and audio chunks
        # of the same video attend to each other inside one packed
        # sequence). When False, the same ``video_*`` data is routed
        # through the regular ``vision`` / ``audio`` encoders independently.
        # Mirrors ``args.video_omni_fusion`` on the megatron side.
        video_omni_fusion=False,
        **kwargs,
    ):
        def _build_sub_config(key, value):
            if value is None:
                return None
            if isinstance(value, dict):
                return self.sub_configs[key](**value)
            return value

        self.audio_config = _build_sub_config("audio_config", audio_config)
        self.vision_config = _build_sub_config("vision_config", vision_config)
        self.omni_config = _build_sub_config("omni_config", omni_config)

        if isinstance(text_config, dict):
            self.text_config = self.sub_configs["text_config"](**text_config)
        elif text_config is None:
            self.text_config = self.sub_configs["text_config"]()
        else:
            self.text_config = text_config

        # self.image_token_id = image_token_id
        # self.video_token_id = video_token_id
        # self.audio_token_id = audio_token_id
        # self.image_pad_token_id = image_pad_token_id
        # self.audio_pad_token_id = audio_pad_token_id
        # self.vision_start_token_id = vision_start_token_id
        # self.vision_end_token_id = vision_end_token_id

        self.tie_word_embeddings = tie_word_embeddings
        self.video_omni_fusion = video_omni_fusion
        super().__init__(**kwargs)


__all__ = ["YoutuVITAConfig", "YoutuVITAOmniConfig"]
