#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/youtu_vita/modular_youtu_vita.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_youtu_vita.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the Tencent and HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
import os

import numpy as np
import PIL.Image
import torch

from ...image_processing_utils import BaseImageProcessor
from .modeling_youtu_vita import Youtu_VITA_TOKEN
from .processing_youtu_vita import YoutuVITAImagesKwargs
from .tokenization_youtu_vita import VisionTokenizer


# _GLOBAL_TOKEN = Qwen3_VITA_TOKEN()
_GLOBAL_TOKEN = Youtu_VITA_TOKEN()


def get_token():
    _ensure_var_is_initialized(_GLOBAL_TOKEN, "token")
    return _GLOBAL_TOKEN


def _ensure_var_is_initialized(var, name):
    """Make sure the input variable is not None."""
    assert var is not None, f"{name} is not initialized."


def get_vision_tokenizer(model_name_or_path_list, vision_tokenizer_type_list, rank=None):
    if vision_tokenizer_type_list is None:
        vision_tokenizer_type_list = []
        model_name_or_path_list = []

    tokenizer_contiguous = None
    tokenizer_discrete = None
    for vision_tokenizer_type, model_name_or_path in zip(vision_tokenizer_type_list, model_name_or_path_list):
        if vision_tokenizer_type == "pixel":
            tokenizer_contiguous = True

        elif vision_tokenizer_type == "chameleon":
            # from .chameleon import update_tokenizer_for_chameleon, ChameleonTokenizer

            tokenizer_discrete = ChameleonTokenizer(model_name_or_path, rank=rank)

        elif vision_tokenizer_type == "emu35":
            # from .emu35 import update_tokenizer_for_emu35, Emu35Tokenizer

            tokenizer_discrete = Emu35Tokenizer(model_name_or_path, rank=rank)

        else:
            print(f"{vision_tokenizer_type_list=}")
            raise NotImplementedError

    vision_tokenizer = VisionTokenizer(tokenizer_contiguous, tokenizer_discrete)
    return vision_tokenizer


# https://github.com/QwenLM/Qwen3-VL/blob/main/qwen-vl-utils/src/qwen_vl_utils/vision_process.py
def smart_resize(
    height: int,
    width: int,
    factor: int = 28,
    min_pixels: int = 56 * 56,
    max_pixels: int = 14 * 14 * 4 * 1280,
):
    """Rescales the image so that the following conditions are met:

    1. Both dimensions (height and width) are divisible by 'factor'.

    2. The total number of pixels is within the range ['min_pixels', 'max_pixels'].

    3. The aspect ratio of the image is maintained as closely as possible.

    """
    if max(height, width) / min(height, width) > 200:
        raise ValueError(
            f"absolute aspect ratio must be smaller than 200, got {max(height, width) / min(height, width)}"
        )
    h_bar = round(height / factor) * factor
    w_bar = round(width / factor) * factor
    if h_bar * w_bar > max_pixels:
        beta = math.sqrt((height * width) / max_pixels)
        h_bar = max(factor, math.floor(height / beta / factor) * factor)
        w_bar = max(factor, math.floor(width / beta / factor) * factor)
    elif h_bar * w_bar < min_pixels:
        beta = math.sqrt(min_pixels / (height * width))
        h_bar = math.ceil(height * beta / factor) * factor
        w_bar = math.ceil(width * beta / factor) * factor
    return h_bar, w_bar


class YoutuVITAImageProcessor(BaseImageProcessor):
    model_input_names = ["images", "image_indices", "image_grid_thw"]
    valid_kwargs = YoutuVITAImagesKwargs

    def __init__(
        self,
        image_size=448,
        image_size_discrete=None,
        vision_normalize_type="imagenet",
        vision_resolution_type="dynamic",
        min_tile_grid=1,
        max_tile_grid=6,
        image_min_num_tokens=4,
        image_max_num_tokens=256,
        temporal_patch_size=1,
        spatial_merge_size=2,
        patch_size=14,
        vision_tokenizer_path=None,
        vision_tokenizer_type=None,
        **kwargs,
    ) -> None:
        super().__init__(**kwargs)
        self.image_size = image_size
        self.image_size_discrete = image_size_discrete
        self.vision_resolution_type = vision_resolution_type
        self.min_tile_grid = min_tile_grid
        self.max_tile_grid = max_tile_grid
        self.tile_image_size = image_size
        self.image_max_num_tokens = image_max_num_tokens
        self.image_min_num_tokens = image_min_num_tokens

        GLOBAL_TOKEN = get_token()
        if vision_normalize_type == "imagenet":
            MEAN, STD = GLOBAL_TOKEN.IMAGENET_DEFAULT_MEAN, GLOBAL_TOKEN.IMAGENET_DEFAULT_STD
        elif vision_normalize_type == "clip":
            MEAN, STD = GLOBAL_TOKEN.OPENAI_CLIP_MEAN, GLOBAL_TOKEN.OPENAI_CLIP_STD
        elif vision_normalize_type == "siglip":
            MEAN, STD = GLOBAL_TOKEN.IMAGENET_STANDARD_MEAN, GLOBAL_TOKEN.IMAGENET_STANDARD_STD
        else:
            raise NotImplementedError(vision_normalize_type)
        self.mean = MEAN
        self.std = STD

        if self.vision_resolution_type == "anyres":
            raise NotImplementedError
            self.grid_pinpoints = [
                (i, j)
                for i in range(min_tile_grid, max_tile_grid + 1)
                for j in range(min_tile_grid, max_tile_grid + 1)
            ]
            self.possible_resolutions = [[dim * self.tile_image_size for dim in pair] for pair in self.grid_pinpoints]
            print(f"{self.grid_pinpoints=}")
            print(f"{self.possible_resolutions=}")

        if self.vision_resolution_type == "dynamic":
            max_num = self.max_tile_grid
            min_num = self.min_tile_grid
            # calculate the existing image aspect ratio
            target_ratios = set(
                (i, j)
                for n in range(min_num, max_num + 1)
                for i in range(1, n + 1)
                for j in range(1, n + 1)
                if i * j <= max_num and i * j >= min_num
            )
            self.target_ratios = sorted(target_ratios, key=lambda x: x[0] * x[1])
            self.possible_resolutions = [[dim * self.tile_image_size for dim in pair] for pair in self.target_ratios]
            print(f"{self.target_ratios=}")
            print(f"{self.possible_resolutions=}")

        if self.vision_resolution_type == "native":
            self.min_pixels = (patch_size * spatial_merge_size) ** 2 * image_min_num_tokens
            self.max_pixels = (patch_size * spatial_merge_size) ** 2 * image_max_num_tokens
            print(f"{self.min_pixels=} {self.max_pixels=}")

        self.patch_size = patch_size
        self.temporal_patch_size = temporal_patch_size
        self.spatial_merge_size = spatial_merge_size

        self.vision_tokenizer = get_vision_tokenizer(
            vision_tokenizer_path,
            vision_tokenizer_type,
            rank=None,
        )

    def to_dict(self):
        output = super().to_dict()
        # Remove the non-serializable object before returning
        if "vision_tokenizer" in output:
            del output["vision_tokenizer"]
        return output

    def load_model(self):
        self.vision_tokenizer.load_model()

    def process_images_to_tensor(self, image_or_path_list):
        if isinstance(image_or_path_list[0], str):
            images = [PIL.Image.open(x).convert("RGB") for x in image_or_path_list]
        elif isinstance(image_or_path_list[0], PIL.Image.Image):
            images = [x.convert("RGB") for x in image_or_path_list]
        else:
            images = image_or_path_list

        def expand2square(pil_img, background_color):
            width, height = pil_img.size
            if width == height:
                return pil_img
            elif width > height:
                result = PIL.Image.new(pil_img.mode, (width, width), background_color)
                result.paste(pil_img, (0, (width - height) // 2))
                return result
            else:
                result = PIL.Image.new(pil_img.mode, (height, height), background_color)
                result.paste(pil_img, ((height - width) // 2, 0))
                return result

        image_tensor = torch.ones([len(images), 3, self.image_size, self.image_size])

        for i, image in enumerate(images):
            image = expand2square(image, tuple(int(x * 255) for x in self.mean))

            image = image.resize((self.image_size, self.image_size), resample=PIL.Image.Resampling.BICUBIC)

            image = np.array(image, dtype=np.float32)
            image = image * 1.0 / 255.0

            mean = np.array(self.mean, dtype=image.dtype)
            std = np.array(self.std, dtype=image.dtype)
            image = (image - mean) / std

            image = torch.tensor(image, dtype=torch.float32)
            image = image.permute(2, 0, 1)

            image_tensor[i] = image

        return {
            "images": image_tensor,
            "image_height": self.image_size,
            "image_width": self.image_size,
        }
        return image_tensor, (self.image_size, self.image_size)

    def process_tensor_to_image(self, image_tensor):
        image_tensor = image_tensor.permute(1, 2, 0)
        image = image_tensor.numpy()

        mean = np.array(self.mean, dtype=image.dtype)
        std = np.array(self.std, dtype=image.dtype)
        image = image * std + mean
        image = image * 255
        image = image.astype(np.uint8)
        image = PIL.Image.fromarray(image)

        return image

    def process_image_to_tiles(self, image_or_path, **kwargs):
        if self.vision_resolution_type == "anyres":
            return self.process_anyres(image_or_path)
        if self.vision_resolution_type == "dynamic":
            return self.process_dynamic(image_or_path)
        if self.vision_resolution_type == "native":
            return self.process_native(image_or_path, **kwargs)

        if isinstance(image_or_path, str):
            image = PIL.Image.open(image_or_path).convert("RGB")
        elif isinstance(image_or_path, PIL.Image.Image):
            image = image_or_path.convert("RGB")
        else:
            image = image_or_path

        return self.process_images_to_tensor([image])

    def process_image(self, image_or_path, is_discrete=False, is_contiguous=False, **kwargs):
        assert not (is_discrete and is_contiguous)
        assert is_discrete or is_contiguous

        if is_discrete and self.vision_tokenizer.tokenizer_discrete is not None:
            if isinstance(image_or_path, str):
                tokenizer_type = self.vision_tokenizer.tokenizer_discrete.tokenizer_type

                if "image_height" in kwargs and "image_width" in kwargs:
                    image_height = kwargs["image_height"]
                    image_width = kwargs["image_width"]
                    suffix = f"-{image_height=}-{image_width=}-{tokenizer_type}.json"

                else:
                    area = self.image_size_discrete * self.image_size_discrete
                    kwargs["area"] = area
                    suffix = f"-{area=}-{tokenizer_type}.json"

                cache_path = os.path.splitext(image_or_path)[0] + suffix
                image_data = load_cache(cache_path)
                if image_data:
                    return image_data

            image_data = self.vision_tokenizer.encode(
                image_or_path,
                is_discrete=is_discrete,
                is_contiguous=is_contiguous,
                **kwargs,
            )
            image_data["image_tokens"] = image_data["image_tokens"].tolist()

            if isinstance(image_or_path, str):
                save_cache(image_data, cache_path)

            return image_data

        if is_contiguous:
            vision_resolution_type = kwargs.get("vision_resolution_type", self.vision_resolution_type)
            if self.vision_resolution_type == "anyres":
                return self.process_anyres(image_or_path)
            if self.vision_resolution_type == "dynamic":
                return self.process_dynamic(image_or_path)
            if self.vision_resolution_type == "native":
                return self.process_native(image_or_path, **kwargs)

            if isinstance(image_or_path, str):
                image = PIL.Image.open(image_or_path).convert("RGB")
            elif isinstance(image_or_path, PIL.Image.Image):
                image = image_or_path.convert("RGB")
            else:
                image = image_or_path

            return self.process_images_to_tensor([image])

    def process_images(self, image_or_paths, is_discrete=False, is_contiguous=False, **kwargs):
        images = []
        best_width = None
        best_height = None
        for image_or_path in image_or_paths:
            image_data = self.process_image(
                image_or_path, is_discrete=is_discrete, is_contiguous=is_contiguous, **kwargs
            )
            _images = image_data["images"]
            best_width = image_data["image_width"]
            best_height = image_data["image_height"]
            images.append(_images)

        images = torch.cat(images, dim=0)
        return {
            "images": images,
            "image_height": best_height,
            "image_width": best_width,
        }
        return images, (best_width, best_height)

    def process_token_to_image(self, image_tokens, **kwargs):
        image_data = self.vision_tokenizer.decode(image_tokens, **kwargs)
        return image_data

    def process_anyres(self, image_or_path):
        if isinstance(image_or_path, str):
            image = PIL.Image.open(image_or_path).convert("RGB")
        elif isinstance(image_or_path, PIL.Image.Image):
            image = image_or_path.convert("RGB")
        else:
            image = image_or_path

        best_resolution = select_best_resolution(image.size, self.possible_resolutions)
        image_padded = resize_and_pad_image(image, best_resolution)
        patches = divide_to_patches(image_padded, self.tile_image_size)

        if best_resolution == (self.tile_image_size, self.tile_image_size):
            image_patches = [image]
        else:
            image_patches = [image] + patches

        image_patches, _ = self.process_images_to_tensor(image_patches)

        # print(f"image {image.size} best_resolution {best_resolution} image_padded {image_padded.size} patches {len(patches)} image_patches {image_patches.size()}")
        return {
            "images": image_patches,
            "image_height": best_resolution[1],
            "image_width": best_resolution[0],
        }

        return image_patches, best_resolution

    def process_dynamic(self, image_or_path):
        if isinstance(image_or_path, str):
            image = PIL.Image.open(image_or_path).convert("RGB")
        elif isinstance(image_or_path, PIL.Image.Image):
            image = image_or_path.convert("RGB")
        else:
            image = image_or_path

        image_patches, best_resolution = dynamic_preprocess(
            image,
            min_num=self.min_tile_grid,
            max_num=self.max_tile_grid,
            image_size=self.tile_image_size,
            use_thumbnail=True,
        )

        image_data = self.process_images_to_tensor(image_patches)
        image_patches = image_data["images"]

        # print(f"{image.size()=} {best_resolution=} {image_patches.size()=}")
        return {
            "images": image_patches,
            "image_height": best_resolution[1],
            "image_width": best_resolution[0],
        }

        return image_patches, best_resolution

    def process_native(self, image_or_path, **kwargs):
        if isinstance(image_or_path, str):
            image = PIL.Image.open(image_or_path).convert("RGB")
        elif isinstance(image_or_path, PIL.Image.Image):
            image = image_or_path.convert("RGB")
        else:
            image = image_or_path

        width, height = image.size

        min_pixels = kwargs.get("min_pixels", self.min_pixels)
        max_pixels = kwargs.get("max_pixels", self.max_pixels)

        factor = self.patch_size * self.spatial_merge_size
        resized_height, resized_width = smart_resize(
            height,
            width,
            factor=factor,
            min_pixels=min_pixels,
            max_pixels=max_pixels,
        )
        # if height - factor > resized_height or width - factor > resized_width:
        #     print(f"Image is downsampled: {height=} {width=} {resized_height=} {resized_width=}", flush=True)

        # resized_height, resized_width = get_image_size_for_max_num_patches(
        #     height,
        #     width,
        #     patch_size=self.patch_size * self.spatial_merge_size,
        #     max_num_patches=self.image_max_num_tokens,
        # )

        image = image.resize((resized_width, resized_height), resample=PIL.Image.Resampling.BICUBIC)

        image = np.array(image, dtype=np.float32)
        image = image * 1.0 / 255.0

        mean = np.array(self.mean, dtype=image.dtype)
        std = np.array(self.std, dtype=image.dtype)
        image = (image - mean) / std

        image = torch.tensor(image, dtype=torch.float32)
        image = image.permute(2, 0, 1)

        # print(f"{image.size()=} {resized_width=} {resized_height=}")

        return {
            "images": image[None, ...],
            "image_height": resized_height,
            "image_width": resized_width,
        }

        return image[None, ...], (resized_width, resized_height)

    def convert_image_to_patches_with_pixel_shuffle(self, image):
        """
        image: (num_channels, image_height, image_width)
        patched_image: (_, patch_size * patch_size * num_channels)
        """

        patches = image[None, ...]
        _, num_channels, image_height, image_width = patches.shape

        channel = patches.shape[1]
        grid_t = patches.shape[0] // self.temporal_patch_size
        grid_h, grid_w = image_height // self.patch_size, image_width // self.patch_size
        patches = patches.reshape(
            grid_t,
            self.temporal_patch_size,
            channel,
            grid_h // self.spatial_merge_size,
            self.spatial_merge_size,
            self.patch_size,
            grid_w // self.spatial_merge_size,
            self.spatial_merge_size,
            self.patch_size,
        )
        patches = patches.permute(
            0, 3, 6, 4, 7, 2, 1, 5, 8
        )  # grid_t, grid_h // merge_size, grid_w // merge_size, merge_size, merge_size, channel, temporal_patch_size, patch_size, patch_size
        flatten_patches = patches.reshape(
            grid_t * grid_h * grid_w,
            channel * self.temporal_patch_size * self.patch_size * self.patch_size,
        )

        return flatten_patches

    def get_image_grid_thw(self, images):
        image_grid_thw = []
        for image in images:
            assert isinstance(images, torch.Tensor)
            _, height, width = image.shape

            grid_t = 1 // self.temporal_patch_size
            grid_h = height // self.patch_size
            grid_w = width // self.patch_size

            image_grid_thw.append([grid_t, grid_h, grid_w])
        # image_grid_thw = torch.tensor(image_grid_thw, dtype=torch.int64)

        return image_grid_thw

    @property
    def is_discrete(self):
        return self.vision_tokenizer.is_discrete

    @property
    def is_contiguous(self):
        return self.vision_tokenizer.is_contiguous

    def get_resize_factor(self, image_or_path):
        if isinstance(image_or_path, str):
            image = PIL.Image.open(image_or_path).convert("RGB")
        elif isinstance(image_or_path, PIL.Image.Image):
            image = image_or_path.convert("RGB")
        else:
            image = image_or_path

        width, height = image.size
        image_data = self.process_image(image_or_path, is_contiguous=True)
        best_width = image_data["image_width"]
        best_height = image_data["image_height"]

        scale_x = 1.0 * best_width / width
        scale_y = 1.0 * best_height / height

        return scale_x, scale_y

    def add_image_input_contiguous(
        self,
        input_ids,
        image_or_paths,
        tokenizer,
        # image_token_length=256,
        targets=None,
        is_pretrain=False,
        **kwargs,
    ):
        GLOBAL_TOKEN = get_token()

        IMG_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.IMG_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        IMG_START_ID = tokenizer(GLOBAL_TOKEN.IMG_START_TOKEN, add_special_tokens=False).input_ids
        IMG_END_ID = tokenizer(GLOBAL_TOKEN.IMG_END_TOKEN, add_special_tokens=False).input_ids

        PATCH_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.PATCH_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        PATCH_START_ID = tokenizer(GLOBAL_TOKEN.PATCH_START_TOKEN, add_special_tokens=False).input_ids
        PATCH_END_ID = tokenizer(GLOBAL_TOKEN.PATCH_END_TOKEN, add_special_tokens=False).input_ids

        IMG_TAG_ID = tokenizer(GLOBAL_TOKEN.IMG_TAG_TOKEN, add_special_tokens=False).input_ids

        assert len(IMG_CONTEXT_ID) == 1
        assert len(IMG_START_ID) == 1
        assert len(IMG_END_ID) == 1

        assert len(PATCH_CONTEXT_ID) == 1
        assert len(PATCH_START_ID) == 1
        assert len(PATCH_END_ID) == 1

        IMG_CONTEXT_ID = IMG_CONTEXT_ID[0]
        IMG_START_ID = IMG_START_ID[0]
        IMG_END_ID = IMG_END_ID[0]

        PATCH_CONTEXT_ID = PATCH_CONTEXT_ID[0]
        PATCH_START_ID = PATCH_START_ID[0]
        PATCH_END_ID = PATCH_END_ID[0]

        IMG_TAG_ID = IMG_TAG_ID[0]

        nl_tokens = tokenizer("\n", add_special_tokens=False).input_ids

        img_positions = [i for i, x in enumerate(input_ids) if x == IMG_TAG_ID]

        images = []
        image_indices = []
        image_grid_thw = []

        new_input_ids = []
        new_targets = []

        st = 0
        for img_idx, img_pos in enumerate(img_positions):
            (
                image_patches,
                (best_width, best_height),
            ) = self.process_image_to_tiles(image_or_paths[img_idx])
            # image_patches, _ = self.process_images_to_tensor([image_or_paths[img_idx]])

            _image_grid_thw = self.get_image_grid_thw(image_patches)

            if self.vision_resolution_type == "native":
                images.append(
                    torch.cat(
                        [self.convert_image_to_patches_with_pixel_shuffle(x) for x in image_patches],
                        dim=0,
                    )
                )
            else:
                images.append(image_patches)

            new_input_ids += input_ids[st:img_pos]
            if targets is not None:
                new_targets += targets[st:img_pos]

            new_input_ids += [IMG_START_ID]
            if targets is not None:
                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            image_token_length = (
                _image_grid_thw[0][0]
                * _image_grid_thw[0][1]
                * _image_grid_thw[0][2]
                // self.spatial_merge_size
                // self.spatial_merge_size
            )
            image_indice_b = torch.zeros(1, image_token_length, dtype=torch.int64)  # This will change in collate_fn
            image_indice_s = (
                torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length).unsqueeze(0).repeat(1, 1)
            )
            image_indice_b_s = torch.stack([image_indice_b, image_indice_s], dim=0)  # 2, num_image, image_length
            if self.vision_resolution_type == "native":
                image_indices.append(image_indice_b_s.view(2, -1))
            else:
                image_indices.append(image_indice_b_s)

            new_input_ids += [IMG_CONTEXT_ID] * image_token_length
            if targets is not None:
                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

            new_input_ids += [IMG_END_ID]
            if targets is not None:
                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            if len(image_patches) > 1:
                for _ in range(0, best_height, self.tile_image_size):
                    new_input_ids += nl_tokens
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

                    for _ in range(0, best_width, self.tile_image_size):
                        new_input_ids += [PATCH_START_ID]
                        if targets is not None:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                        image_indice_b = torch.zeros(
                            1, image_token_length, dtype=torch.int64
                        )  # This will change in collate_fn
                        image_indice_s = (
                            torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                            .unsqueeze(0)
                            .repeat(1, 1)
                        )
                        image_indice_b_s = torch.stack(
                            [image_indice_b, image_indice_s], dim=0
                        )  # 2, num_image, image_length
                        image_indices.append(image_indice_b_s)

                        new_input_ids += [PATCH_CONTEXT_ID] * image_token_length
                        if targets is not None:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                        new_input_ids += [PATCH_END_ID]
                        if targets is not None:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            image_grid_thw.extend(_image_grid_thw)
            st = img_pos + 1

        new_input_ids += input_ids[st:]
        if targets is not None:
            new_targets += targets[st:]

        input_ids = new_input_ids
        if targets is not None:
            targets = new_targets

        image_grid_thw = torch.tensor(image_grid_thw, dtype=torch.long)

        if targets is not None:
            return input_ids, images, image_indices, image_grid_thw, targets

        images = torch.cat(images, dim=0)
        image_indices = torch.cat(image_indices, dim=1)

        image_indices = image_indices.contiguous().to(torch.cuda.current_device())
        if True:
            images = torch.tensor(images, dtype=torch.bfloat16).contiguous().to(torch.cuda.current_device())

        else:
            images = torch.tensor(images, dtype=torch.float16).contiguous().to(torch.cuda.current_device())

        return input_ids, images, image_indices, image_grid_thw

    def add_image_input_discrete_and_contiguous(
        self,
        input_ids,
        image_or_paths,
        tokenizer,
        # image_token_length=256,
        use_tile=True,
        targets=None,
        is_pretrain=False,
        **kwargs,
    ):
        GLOBAL_TOKEN = get_token()

        IMG_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.IMG_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        IMG_START_ID = tokenizer(GLOBAL_TOKEN.IMG_START_TOKEN, add_special_tokens=False).input_ids
        IMG_END_ID = tokenizer(GLOBAL_TOKEN.IMG_END_TOKEN, add_special_tokens=False).input_ids

        PATCH_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.PATCH_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        PATCH_START_ID = tokenizer(GLOBAL_TOKEN.PATCH_START_TOKEN, add_special_tokens=False).input_ids
        PATCH_END_ID = tokenizer(GLOBAL_TOKEN.PATCH_END_TOKEN, add_special_tokens=False).input_ids

        IMG_TAG_ID = tokenizer(GLOBAL_TOKEN.IMG_TAG_TOKEN, add_special_tokens=False).input_ids

        IMG_FIRST_ID = tokenizer.convert_tokens_to_ids("<|vision_0|>")
        IMG_EOL_ID = tokenizer.convert_tokens_to_ids("<|vision_eol|>")

        assert len(IMG_CONTEXT_ID) == 1
        assert len(IMG_START_ID) == 1
        assert len(IMG_END_ID) == 1

        assert len(PATCH_CONTEXT_ID) == 1
        assert len(PATCH_START_ID) == 1
        assert len(PATCH_END_ID) == 1

        IMG_CONTEXT_ID = IMG_CONTEXT_ID[0]
        IMG_START_ID = IMG_START_ID[0]
        IMG_END_ID = IMG_END_ID[0]

        PATCH_CONTEXT_ID = PATCH_CONTEXT_ID[0]
        PATCH_START_ID = PATCH_START_ID[0]
        PATCH_END_ID = PATCH_END_ID[0]

        IMG_TAG_ID = IMG_TAG_ID[0]

        nl_tokens = tokenizer("\n", add_special_tokens=False).input_ids

        img_positions = [i for i, x in enumerate(input_ids) if x == IMG_TAG_ID]

        images = []
        image_indices = []
        image_grid_thw = []

        new_input_ids = []
        new_targets = []

        st = 0
        for img_idx, img_pos in enumerate(img_positions):
            new_input_ids += input_ids[st:img_pos]
            if targets is not None:
                new_targets += targets[st:img_pos]

            if use_tile:
                (
                    image_patches,
                    (best_width, best_height),
                ) = self.process_image_to_tiles(image_or_paths[img_idx])
                patch_idx = 0
            else:
                image_patches, _ = self.process_images_to_tensor([image_or_paths[img_idx]])

            _image_grid_thw = self.get_image_grid_thw(image_patches)

            if self.vision_resolution_type == "native":
                images.append(
                    torch.cat(
                        [self.convert_image_to_patches_with_pixel_shuffle(x) for x in image_patches],
                        dim=0,
                    )
                )
            else:
                images.append(image_patches)

            # --------------------------------------------------------------------------
            # add discrete

            if use_tile:
                image_patch = self.process_tensor_to_image(image_patches[patch_idx])
                patch_idx += 1
            else:
                image_patch = image_or_paths[img_idx]
            image_data = self.process_image(image_patch, is_discrete=True)
            image_tokens = image_data["image_tokens"]
            # h, w = image_tokens.shape
            h, w = len(image_token), len(image_token[0])
            # image_tokens = image_tokens.tolist()
            image_input_ids = []
            for _h in range(h):
                for _w in range(w):
                    image_input_ids.append(image_tokens[_h][_w] + IMG_FIRST_ID)
                if _h < h - 1:
                    image_input_ids += [IMG_EOL_ID]

            size_input_ids = tokenizer(f"{h}*{w}", add_special_tokens=False).input_ids

            new_input_ids += [IMG_START_ID]
            if targets is not None:
                if is_pretrain:
                    new_targets += [IMG_START_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            new_input_ids += size_input_ids
            if targets is not None:
                if is_pretrain:
                    new_targets += size_input_ids
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(size_input_ids)

            new_input_ids += image_input_ids
            if targets is not None:
                if is_pretrain:
                    new_targets += image_input_ids
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(image_input_ids)

            new_input_ids += [IMG_END_ID]
            if targets is not None:
                if is_pretrain:
                    new_targets += [IMG_END_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            # --------------------------------------------------------------------------
            # add contiguous

            new_input_ids += [IMG_START_ID]
            if targets is not None:
                if is_pretrain:
                    new_targets += [IMG_START_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            image_token_length = (
                _image_grid_thw[0][0]
                * _image_grid_thw[0][1]
                * _image_grid_thw[0][2]
                // self.spatial_merge_size
                // self.spatial_merge_size
            )
            image_indice_b = torch.zeros(1, image_token_length, dtype=torch.int64)  # This will change in collate_fn
            image_indice_s = (
                torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length).unsqueeze(0).repeat(1, 1)
            )
            image_indice_b_s = torch.stack([image_indice_b, image_indice_s], dim=0)  # 2, num_image, image_length
            if self.vision_resolution_type == "native":
                image_indices.append(image_indice_b_s.view(2, -1))
            else:
                image_indices.append(image_indice_b_s)

            new_input_ids += [IMG_CONTEXT_ID] * image_token_length
            if targets is not None:
                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

            new_input_ids += [IMG_END_ID]
            if targets is not None:
                if is_pretrain:
                    new_targets += [IMG_END_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            if len(image_patches) > 1:
                for _ in range(0, best_height, self.tile_image_size):
                    new_input_ids += nl_tokens
                    if targets is not None:
                        if is_pretrain:
                            new_targets += nl_tokens
                        else:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

                    for _ in range(0, best_width, self.tile_image_size):
                        # --------------------------------------------------------------------------
                        # add discrete

                        image_patch = self.process_tensor_to_image(image_patches[patch_idx])
                        patch_idx += 1
                        image_data = self.process_image(image_patch, is_discrete=True)
                        image_tokens = image_data["image_tokens"]
                        # h, w = image_tokens.shape
                        h, w = len(image_token), len(image_token[0])
                        # image_tokens = image_tokens.tolist()
                        image_input_ids = []
                        for _h in range(h):
                            for _w in range(w):
                                image_input_ids.append(image_tokens[_h][_w] + IMG_FIRST_ID)
                            if _h < h - 1:
                                image_input_ids += [IMG_EOL_ID]

                        size_input_ids = tokenizer(f"{h}*{w}", add_special_tokens=False).input_ids

                        new_input_ids += [PATCH_START_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [PATCH_START_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                        new_input_ids += size_input_ids
                        if targets is not None:
                            if is_pretrain:
                                new_targets += size_input_ids
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(size_input_ids)

                        new_input_ids += image_input_ids
                        if targets is not None:
                            if is_pretrain:
                                new_targets += image_input_ids
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(image_input_ids)

                        new_input_ids += [PATCH_END_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [PATCH_END_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                        # --------------------------------------------------------------------------
                        # add contiguous

                        new_input_ids += [PATCH_START_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [PATCH_START_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                        image_indice_b = torch.zeros(
                            1, image_token_length, dtype=torch.int64
                        )  # This will change in collate_fn
                        image_indice_s = (
                            torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                            .unsqueeze(0)
                            .repeat(1, 1)
                        )
                        image_indice_b_s = torch.stack(
                            [image_indice_b, image_indice_s], dim=0
                        )  # 2, num_image, image_length
                        image_indices.append(image_indice_b_s)

                        new_input_ids += [PATCH_CONTEXT_ID] * image_token_length
                        if targets is not None:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                        new_input_ids += [PATCH_END_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [PATCH_END_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            image_grid_thw.extend(_image_grid_thw)

            # --------------------------------------------------------------------------

            st = img_pos + 1

        new_input_ids += input_ids[st:]
        if targets is not None:
            new_targets += targets[st:]

        input_ids = new_input_ids
        if targets is not None:
            targets = new_targets

        image_grid_thw = torch.tensor(image_grid_thw, dtype=torch.long)

        if targets is not None:
            return input_ids, images, image_indices, image_grid_thw, targets

        images = torch.cat(images, dim=0)
        image_indices = torch.cat(image_indices, dim=1)

        image_indices = image_indices.contiguous().to(torch.cuda.current_device())
        if True:
            images = torch.tensor(images, dtype=torch.bfloat16).contiguous().to(torch.cuda.current_device())

        else:
            images = torch.tensor(images, dtype=torch.float16).contiguous().to(torch.cuda.current_device())

        return input_ids, images, image_indices, image_grid_thw

    def add_image_input_discrete_or_contiguous(
        self,
        input_ids,
        image_or_paths,
        tokenizer,
        # image_token_length=256,
        # use_tile=True,
        discrete_image_idxs=[],
        contiguous_image_idxs=[],
        targets=None,
        is_pretrain=False,
        **kwargs,
    ):
        GLOBAL_TOKEN = get_token()

        IMG_CONTEXT_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_CONTEXT_TOKEN)
        IMG_START_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_START_TOKEN)
        IMG_END_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_END_TOKEN)
        IMG_TAG_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_TAG_TOKEN)

        if self.vision_resolution_type == "native":
            pass
        else:
            PATCH_CONTEXT_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.PATCH_CONTEXT_TOKEN)
            PATCH_START_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.PATCH_START_TOKEN)
            PATCH_END_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.PATCH_END_TOKEN)

        if self.vision_tokenizer.first_vision_token is not None:
            IMG_FIRST_ID = tokenizer.convert_tokens_to_ids(self.vision_tokenizer.first_vision_token)
            IMG_EOL_ID = tokenizer.convert_tokens_to_ids("<|vision_eol|>")

        nl_tokens = tokenizer("\n", add_special_tokens=False).input_ids

        img_positions = [i for i, x in enumerate(input_ids) if x == IMG_TAG_ID]

        if not discrete_image_idxs and not contiguous_image_idxs:
            contiguous_image_idxs = list(range(len(image_or_paths)))

        images = []
        image_indices = []
        image_grid_thw = []

        new_input_ids = []
        new_targets = []

        st = 0
        for img_idx, img_pos in enumerate(img_positions):
            new_input_ids += input_ids[st:img_pos]
            if targets is not None:
                new_targets += targets[st:img_pos]

            # --------------------------------------------------------------------------
            # add discrete
            if img_idx in discrete_image_idxs:
                assert self.vision_resolution_type == "native"
                image_data = self.process_image(
                    image_or_paths[img_idx],
                    is_contiguous=True,
                    min_pixels=self.min_pixels,
                    max_pixels=self.max_pixels // (self.spatial_merge_size * self.spatial_merge_size * 8 * 8),
                )
                image_height = image_data["image_height"]
                image_width = image_data["image_width"]
                image_data = self.process_image(
                    image_or_paths[img_idx],
                    is_discrete=True,
                    image_height=image_height,
                    image_width=image_width,
                )
                image_tokens = image_data["image_tokens"]
                image_height = image_data["image_height"]
                image_width = image_data["image_width"]

                resolution = f"{image_height}*{image_width}"
                size_input_ids = tokenizer(resolution, add_special_tokens=False).input_ids

                image_input_ids = []
                for image_token in image_tokens:
                    image_input_ids += [_ + IMG_FIRST_ID for _ in image_token]
                    image_input_ids += [IMG_EOL_ID]

                new_input_ids += [IMG_START_ID]
                if targets is not None:
                    new_targets += [IMG_START_ID]

                new_input_ids += size_input_ids
                if targets is not None:
                    new_targets += size_input_ids

                new_input_ids += [IMG_EOL_ID]
                if targets is not None:
                    new_targets += [IMG_EOL_ID]

                new_input_ids += image_input_ids
                if targets is not None:
                    new_targets += image_input_ids

                new_input_ids += [IMG_END_ID]
                if targets is not None:
                    new_targets += [IMG_END_ID]

            # --------------------------------------------------------------------------
            # add contiguous
            if img_idx in contiguous_image_idxs:
                image_data = self.process_image(image_or_paths[img_idx], is_contiguous=True)
                image_patches = image_data["images"]
                best_width = image_data["image_width"]
                best_height = image_data["image_height"]

                _image_grid_thw = self.get_image_grid_thw(image_patches)
                image_grid_thw.extend(_image_grid_thw)

                if self.vision_resolution_type == "native":
                    images.append(
                        torch.cat(
                            [self.convert_image_to_patches_with_pixel_shuffle(x) for x in image_patches],
                            dim=0,
                        )
                    )
                else:
                    images.append(image_patches)

                new_input_ids += [IMG_START_ID]
                if targets is not None:
                    if is_pretrain:
                        new_targets += [IMG_START_ID]
                    else:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                if self.vision_resolution_type == "native":
                    resolution = f"{_image_grid_thw[0][1] * self.patch_size}*{_image_grid_thw[0][2] * self.patch_size}"
                    size_input_id = tokenizer(resolution, add_special_tokens=False).input_ids
                    new_input_ids += size_input_id
                    if targets is not None:
                        if is_pretrain:
                            # new_targets += size_input_id
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(size_input_id)
                        else:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(size_input_id)

                    new_input_ids += nl_tokens
                    if targets is not None:
                        if is_pretrain:
                            new_targets += [IMG_EOL_ID]
                        else:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

                    for _h in range(_image_grid_thw[0][0] * _image_grid_thw[0][1] // self.spatial_merge_size):
                        image_token_length = _image_grid_thw[0][2] // self.spatial_merge_size
                        image_indice_b = torch.zeros(
                            1, image_token_length, dtype=torch.int64
                        )  # This will change in collate_fn
                        image_indice_s = (
                            torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                            .unsqueeze(0)
                            .repeat(1, 1)
                        )
                        image_indice_b_s = torch.stack(
                            [image_indice_b, image_indice_s], dim=0
                        )  # 2, num_image, image_length
                        image_indices.append(image_indice_b_s.view(2, -1))

                        new_input_ids += [IMG_CONTEXT_ID] * image_token_length
                        if targets is not None:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                        new_input_ids += nl_tokens
                        if targets is not None:
                            if is_pretrain:
                                new_targets += nl_tokens
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

                else:
                    image_token_length = (
                        _image_grid_thw[0][0]
                        * _image_grid_thw[0][1]
                        * _image_grid_thw[0][2]
                        // self.spatial_merge_size
                        // self.spatial_merge_size
                    )
                    image_indice_b = torch.zeros(
                        1, image_token_length, dtype=torch.int64
                    )  # This will change in collate_fn
                    image_indice_s = (
                        torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                        .unsqueeze(0)
                        .repeat(1, 1)
                    )
                    image_indice_b_s = torch.stack(
                        [image_indice_b, image_indice_s], dim=0
                    )  # 2, num_image, image_length
                    image_indices.append(image_indice_b_s)

                    new_input_ids += [IMG_CONTEXT_ID] * image_token_length
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                new_input_ids += [IMG_END_ID]
                if targets is not None:
                    if is_pretrain:
                        new_targets += [IMG_END_ID]
                    else:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                if len(image_patches) > 1:
                    for _ in range(0, best_height, self.tile_image_size):
                        new_input_ids += nl_tokens
                        if targets is not None:
                            if is_pretrain:
                                new_targets += nl_tokens
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

                        for _ in range(0, best_width, self.tile_image_size):
                            new_input_ids += [PATCH_START_ID]
                            if targets is not None:
                                if is_pretrain:
                                    new_targets += [PATCH_START_ID]
                                else:
                                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                            image_indice_b = torch.zeros(
                                1, image_token_length, dtype=torch.int64
                            )  # This will change in collate_fn
                            image_indice_s = (
                                torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                                .unsqueeze(0)
                                .repeat(1, 1)
                            )
                            image_indice_b_s = torch.stack(
                                [image_indice_b, image_indice_s], dim=0
                            )  # 2, num_image, image_length
                            image_indices.append(image_indice_b_s)

                            new_input_ids += [PATCH_CONTEXT_ID] * image_token_length
                            if targets is not None:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                            new_input_ids += [PATCH_END_ID]
                            if targets is not None:
                                if is_pretrain:
                                    new_targets += [PATCH_END_ID]
                                else:
                                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            st = img_pos + 1

        new_input_ids += input_ids[st:]
        if targets is not None:
            new_targets += targets[st:]

        input_ids = new_input_ids
        if targets is not None:
            targets = new_targets

        image_grid_thw = torch.tensor(image_grid_thw, dtype=torch.long)

        if targets is not None:
            return input_ids, images, image_indices, image_grid_thw, targets

        images = torch.cat(images, dim=0)
        image_indices = torch.cat(image_indices, dim=1)

        image_indices = image_indices.contiguous().to(torch.cuda.current_device())
        if True:
            images = torch.tensor(images, dtype=torch.bfloat16).contiguous().to(torch.cuda.current_device())

        else:
            images = torch.tensor(images, dtype=torch.float16).contiguous().to(torch.cuda.current_device())

        return input_ids, images, image_indices, image_grid_thw

    def add_image_input_contiguous_to_discrete(
        self,
        input_ids,
        image_or_paths,
        tokenizer,
        targets=None,
        is_pretrain=False,
        **kwargs,
    ):
        assert self.vision_resolution_type == "native"
        GLOBAL_TOKEN = get_token()

        IMG_CONTEXT_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_CONTEXT_TOKEN)
        IMG_START_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_START_TOKEN)
        IMG_END_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_END_TOKEN)
        IMG_TAG_ID = tokenizer.convert_tokens_to_ids(GLOBAL_TOKEN.IMG_TAG_TOKEN)

        if targets is not None:
            IMG_FIRST_ID = tokenizer.convert_tokens_to_ids(self.vision_tokenizer.first_vision_token)
            IMG_EOL_ID = tokenizer.convert_tokens_to_ids("<|vision_eol|>")

        nl_tokens = tokenizer("\n", add_special_tokens=False).input_ids

        img_positions = [i for i, x in enumerate(input_ids) if x == IMG_TAG_ID]

        images = []
        image_indices = []
        image_grid_thw = []

        new_input_ids = []
        new_targets = []

        st = 0
        for img_idx, img_pos in enumerate(img_positions):
            new_input_ids += input_ids[st:img_pos]
            if targets is not None:
                new_targets += targets[st:img_pos]

            image_data = self.process_image(image_or_paths[img_idx], is_contiguous=True)
            image_patches = image_data["images"]
            best_width = image_data["image_width"]
            best_height = image_data["image_height"]

            _image_grid_thw = self.get_image_grid_thw(image_patches)
            image_grid_thw.extend(_image_grid_thw)

            images.append(
                torch.cat(
                    [self.convert_image_to_patches_with_pixel_shuffle(x) for x in image_patches],
                    dim=0,
                )
            )

            if targets is not None:
                image_data = self.process_image(
                    image_or_paths[img_idx],
                    is_discrete=True,
                    image_height=best_height // self.spatial_merge_size,
                    image_width=best_width // self.spatial_merge_size,
                )
                image_tokens = image_data["image_tokens"]
                assert len(image_tokens) == _image_grid_thw[0][1] // self.spatial_merge_size, (
                    f"{len(image_tokens)=} {_image_grid_thw=} {best_width=} {best_height}"
                )
                assert len(image_tokens[0]) == _image_grid_thw[0][2] // self.spatial_merge_size, (
                    f"{len(image_tokens[0])=} {_image_grid_thw=} {best_width=} {best_height}"
                )

            resolution = f"{_image_grid_thw[0][1] * self.patch_size}*{_image_grid_thw[0][2] * self.patch_size}"
            size_input_ids = tokenizer(resolution, add_special_tokens=False).input_ids

            new_input_ids += [IMG_START_ID]
            if targets is not None:
                if is_pretrain:
                    new_targets += [IMG_START_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            new_input_ids += size_input_ids
            if targets is not None:
                if is_pretrain:
                    # new_targets += size_input_ids
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(size_input_ids)
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(size_input_ids)

            new_input_ids += nl_tokens
            if targets is not None:
                if is_pretrain:
                    new_targets += [IMG_EOL_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

            for image_token in image_tokens:
                image_token_length = _image_grid_thw[0][2] // self.spatial_merge_size
                image_indice_b = torch.zeros(
                    1, image_token_length, dtype=torch.int64
                )  # This will change in collate_fn
                image_indice_s = (
                    torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length).unsqueeze(0).repeat(1, 1)
                )
                image_indice_b_s = torch.stack([image_indice_b, image_indice_s], dim=0)  # 2, num_image, image_length
                image_indices.append(image_indice_b_s.view(2, -1))

                new_input_ids += [IMG_CONTEXT_ID] * image_token_length
                if targets is not None:
                    new_targets += [_ + IMG_FIRST_ID for _ in image_token]

                new_input_ids += nl_tokens
                if targets is not None:
                    if is_pretrain:
                        new_targets += [IMG_EOL_ID]
                    else:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

            new_input_ids += [IMG_END_ID]
            if targets is not None:
                if is_pretrain:
                    new_targets += [IMG_END_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            st = img_pos + 1

        new_input_ids += input_ids[st:]
        if targets is not None:
            new_targets += targets[st:]

        input_ids = new_input_ids
        if targets is not None:
            targets = new_targets

        image_grid_thw = torch.tensor(image_grid_thw, dtype=torch.long)

        if targets is not None:
            return input_ids, images, image_indices, image_grid_thw, targets

        images = torch.cat(images, dim=0)
        image_indices = torch.cat(image_indices, dim=1)

        image_indices = image_indices.contiguous().to(torch.cuda.current_device())
        if True:
            images = torch.tensor(images, dtype=torch.bfloat16).contiguous().to(torch.cuda.current_device())

        else:
            images = torch.tensor(images, dtype=torch.float16).contiguous().to(torch.cuda.current_device())

        return input_ids, images, image_indices, image_grid_thw


__all__ = ["YoutuVITAImageProcessor"]
