#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/youtu_vita/modular_youtu_vita.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_youtu_vita.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the Tencent and HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import torch

from ...feature_extraction_utils import BatchFeature
from ...image_utils import ImageInput
from ...processing_utils import ImagesKwargs, ProcessingKwargs, ProcessorMixin, Unpack, VideosKwargs
from ...tokenization_utils_base import AudioInput, PreTokenizedInput, TextInput
from ...video_utils import VideoInput
from .modeling_youtu_vita import YoutuVITAAudioKwargs


class YoutuVITAImagesKwargs(ImagesKwargs, total=False):
    """ """

    discrete_image_idxs: list
    contiguous_image_idxs: list


class YoutuVITAVideosKwargs(VideosKwargs, total=False):
    """ """

    resolution_type: str
    min_num_tokens: int
    max_num_tokens: int
    image_min_num_tokens: int
    image_max_num_tokens: int
    temporal_patch_size: int
    spatial_merge_size: int
    patch_size: int
    video_key_frame: bool
    use_audio_in_video: bool
    use_vision_in_video: bool


class YoutuVITAProcessorKwargs(ProcessingKwargs, total=False):
    images_kwargs: YoutuVITAImagesKwargs
    videos_kwargs: YoutuVITAVideosKwargs
    audio_kwargs: YoutuVITAAudioKwargs

    _defaults = {
        "text_kwargs": {
            "padding": False,
            "padding_side": "left",
        },
        "images_kwargs": {},
        "videos_kwargs": {
            "resolution_type": "native",
            "min_num_tokens": 64,
            "max_num_tokens": 8192,
            "image_min_num_tokens": 4,
            "image_max_num_tokens": 256,
            "temporal_patch_size": 1,
            "spatial_merge_size": 2,
            "patch_size": 16,
            "video_key_frame": False,
            "use_audio_in_video": True,
            "use_vision_in_video": True,
        },
        "audio_kwargs": {
            "sampling_rate": 16000,
            "padding": "max_length",
            "return_attention_mask": True,
        },
    }


class YoutuVITAProcessor(ProcessorMixin):
    def __init__(
        self, image_processor=None, video_processor=None, feature_extractor=None, tokenizer=None, chat_template=None
    ):
        super().__init__(image_processor, video_processor, feature_extractor, tokenizer, chat_template=chat_template)

        audio_processor = feature_extractor
        self.audio_processor = audio_processor

        video_processor.image_processor = image_processor
        video_processor.audio_processor = audio_processor

    def __call__(
        self,
        text: TextInput | PreTokenizedInput | list[TextInput] | list[PreTokenizedInput] = None,
        images_or_paths: ImageInput | None = None,
        videos_or_paths: VideoInput | None = None,
        audios_or_paths: AudioInput | None = None,
        **kwargs: Unpack[YoutuVITAProcessorKwargs],
    ) -> BatchFeature:
        print(f"{text=}")
        print(f"{images_or_paths=}")
        print(f"{videos_or_paths=}")
        print(f"{audios_or_paths=}")
        print(f"{kwargs=}")

        if text is None:
            raise ValueError("You need to specify either a `text` input to process.")

        output_kwargs = self._merge_kwargs(
            YoutuVITAProcessorKwargs,
            tokenizer_init_kwargs=self.tokenizer.init_kwargs,
            **kwargs,
        )
        print(f"{output_kwargs=}")

        texts_inputs = self.tokenizer(text, **output_kwargs["text_kwargs"])
        print(f"{texts_inputs=}")
        input_ids = texts_inputs["input_ids"]

        images_inputs = {}
        videos_inputs = {}
        audio_inputs = {}

        if audios_or_paths:
            input_ids, audios, audio_indices = self.audio_processor.add_audio_input_discrete_or_contiguous(
                input_ids,
                audios_or_paths,
                self.tokenizer,
                discrete_audio_idxs=kwargs.get("discrete_audio_idxs", []),
                **output_kwargs["audio_kwargs"],
            )

            audio_seqlens = [len(x) for x in audios]

            print(
                f"{audios_or_paths=} {len(input_ids)=} {len(audios)=} {sum(x.abs().sum() for x in audios)=} {len(audio_indices)=}"
            )

            audio_inputs["audios"] = audios
            audio_inputs["audio_indices"] = audio_indices
            # audio_inputs["audio_feature_lengths"] = audio_seqlens

        if images_or_paths:
            input_ids, images, image_indices, image_grid_thw = (
                self.image_processor.add_image_input_discrete_or_contiguous(
                    input_ids,
                    images_or_paths,
                    self.tokenizer,
                    # image_token_length=self.image_token_length,
                    **output_kwargs["images_kwargs"],
                )
            )
            print(f"{images_or_paths=} {len(input_ids)=} {images.size()=} {image_indices.size()=} {image_grid_thw=}")

            images_inputs["images"] = images
            images_inputs["image_indices"] = image_indices
            images_inputs["image_grid_thw"] = image_grid_thw

        if videos_or_paths:
            (
                input_ids,
                images,
                image_indices,
                audios,
                audio_indices,
                image_grid_thw,
                second_per_grids,
                # ) = self.video_processor.add_video_input_contiguous(
            ) = self.video_processor.add_video_input_discrete_or_contiguous(
                input_ids,
                videos_or_paths,
                self.tokenizer,
                **output_kwargs["videos_kwargs"],
            )
            if audios is None:
                print(
                    f"{videos_or_paths=} {len(input_ids)=} {images.size()=} {image_indices.size()=} {image_grid_thw.size()=}"
                )
            elif images is None:
                print(
                    f"{videos_or_paths=} {len(input_ids)=} {len(audios)=} {[x.size() for x in audios]=} {len(audio_indices)=}"
                )
            else:
                print(
                    f"{videos_or_paths=} {len(input_ids)=} {images.size()=} {image_indices.size()=} {image_grid_thw.size()=} {len(audios)=} {[x.size() for x in audios]=} {len(audio_indices)=}"
                )

            if audios is None:
                audio_seqlens = None
            else:
                audio_seqlens = [len(x) for x in audios]
            videos_inputs["images"] = images
            videos_inputs["image_indices"] = image_indices
            videos_inputs["audios"] = audios
            videos_inputs["audio_indices"] = audio_indices
            videos_inputs["image_grid_thw"] = image_grid_thw
            # videos_inputs["second_per_grids"] = second_per_grids

        input_ids = torch.tensor([input_ids], dtype=torch.long)
        texts_inputs["input_ids"] = input_ids
        texts_inputs["attention_mask"] = torch.ones_like(input_ids)

        return BatchFeature(
            data={**texts_inputs, **images_inputs, **videos_inputs, **audio_inputs},
            tensor_type=kwargs.get("return_tensors"),
        )

    def apply_chat_template(self, conversations, chat_template=None, **kwargs):
        is_batched = False
        if isinstance(conversations[0], dict):
            conversations = [conversations]
            is_batched = True

        if is_batched:
            conversations = conversations[0]

        return super().apply_chat_template(conversations, chat_template, **kwargs)

    @property
    def model_input_names(self):
        tokenizer_input_names = self.tokenizer.model_input_names
        feature_extractor_input_names = self.feature_extractor.model_input_names
        image_processor_input_names = self.image_processor.model_input_names
        video_processor_input_names = self.video_processor.model_input_names
        return list(
            dict.fromkeys(
                tokenizer_input_names
                + feature_extractor_input_names
                + image_processor_input_names
                + video_processor_input_names
                + ["feature_attention_mask"]
                + ["video_second_per_grid"]
            )
        )


__all__ = ["YoutuVITAProcessor"]
