#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/youtu_vita/modular_youtu_vita.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_youtu_vita.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the Tencent and HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import uuid

import torch
import torchaudio
from funasr.frontends.wav_frontend import WavFrontend
from funasr.utils.load_utils import extract_fbank

from ...utils import logging


logger = logging.get_logger(__name__)


class GLM4VoiceTokenizer:
    sample_rate = 16000

    is_discrete = True
    is_contiguous = False

    _resample_buffer: dict[int, torchaudio.transforms.Resample] = {}

    tokenizer_type = "glm4voice"
    num_codebook = 1
    codebook_size = 16384

    first_audio_token = "<|audio_0|>"
    last_audio_token = "<|audio_16383|>"

    def __init__(self, model_name_or_path, flow_path=None, rank=None):
        self.model_name_or_path = model_name_or_path
        self.flow_path = flow_path

        # if rank is None and torch.distributed.is_initialized():
        #     rank = torch.distributed.get_rank()
        #     rank = rank % 8

        #     CUDA_VISIBLE_DEVICES = os.environ.get('CUDA_VISIBLE_DEVICES', '0,1,2,3,4,5,6,7,8')
        #     gpu_list = [int(x) for x in CUDA_VISIBLE_DEVICES.split(',')]
        #     if rank not in gpu_list:
        #         rank = None

        self.rank = rank
        logger.info(f"{self.rank=}")

    # @torch.compiler.disable
    def load_model(self):
        if not hasattr(self, "whisper_model") and self.model_name_or_path:
            pass
        elif not hasattr(self, "audio_decoder") and self.flow_path:
            pass
        else:
            return

        worker_info = torch.utils.data.get_worker_info()
        if worker_info is not None:
            worker_id = worker_info.id
            num_workers = worker_info.num_workers
            self.rank = worker_id % 8
            logger.info(f"{self.rank=}")

        if self.rank is not None:
            self.device = f"cuda:{self.rank}"
            # torch.cuda.set_device(self.rank)
        else:
            self.device = "cuda"
            # self.device = "cpu"
        # self.device = "cpu"

        logger.info(f"{self.device=}")

        assert isinstance(self.model_name_or_path, str)

        if not hasattr(self, "whisper_model") and self.model_name_or_path:
            assert isinstance(self.model_name_or_path, str)

            from speech_tokenizer.modeling_whisper import WhisperVQEncoder

            logger.info(f"⏳ {self.device=} Loading {self.tokenizer_type} from {self.model_name_or_path}")
            self.whisper_model = WhisperVQEncoder.from_pretrained(self.model_name_or_path).eval().to(self.device)
            self.feature_extractor = WhisperFeatureExtractor.from_pretrained(self.model_name_or_path)
            logger.info(f"⏳ {self.device=} Loading {self.tokenizer_type} Done")

        if not hasattr(self, "audio_decoder") and self.flow_path:
            assert isinstance(self.flow_path, str)

            from .flow_inference import AudioDecoder

            logger.info(f"⏳ {self.device=} Loading zai-org/glm-4-voice-decoder")
            flow_config = os.path.join(self.flow_path, "config.yaml")
            flow_checkpoint = os.path.join(self.flow_path, "flow.pt")
            hift_checkpoint = os.path.join(self.flow_path, "hift.pt")

            # Flow & Hift
            self.audio_decoder = AudioDecoder(
                config_path=flow_config,
                flow_ckpt_path=flow_checkpoint,
                hift_ckpt_path=hift_checkpoint,
                device=self.device,
            )
            logger.info(f"⏳ {self.device=} Loading zai-org/glm-4-voice-decoder Done")

    @torch.no_grad()
    # @torch.compiler.disable
    def encode(self, audio_or_path, **kwargs):
        if not hasattr(self, "whisper_model"):
            self.load_model()

        if True:
            audio_tokens = self.extract_speech_token(
                self.whisper_model, self.feature_extractor, [audio_or_path], device=self.device
            )[0]
            return audio_tokens

        return None

    @torch.no_grad()
    # @torch.compiler.disable
    def decode(self, audio_tokens, option_steps=10, **kwargs):
        if not hasattr(self, "whisper_model"):
            self.load_model()

        this_uuid = str(uuid.uuid4())
        this_uuid = "abc"

        tts_token = torch.tensor(audio_tokens, device=self.device).unsqueeze(0)

        flow_prompt_speech_token = torch.zeros(1, 0, dtype=torch.int64).to(self.device)
        prompt_speech_feat = torch.zeros(1, 0, 80).to(self.device)

        tts_speech, tts_mel = self.audio_decoder.token2wav(
            tts_token,
            uuid=this_uuid,
            prompt_token=flow_prompt_speech_token.to(self.device),
            prompt_feat=prompt_speech_feat.to(self.device),
            finalize=True,
            option_steps=option_steps,
        )
        tts_speechs = []
        tts_speechs.append(tts_speech.squeeze())
        tts_speech = torch.cat(tts_speechs, dim=-1).cpu()

        return tts_speech

    # @torch.compiler.disable
    def extract_speech_token(self, model, feature_extractor, utts, device="cuda"):
        with torch.no_grad():
            audios, indices = [], []
            for idx, utt in enumerate(utts):
                if isinstance(utt, tuple):
                    audio, sample_rate = utt
                else:
                    audio, sample_rate = torchaudio.load(utt)
                # audio = audio.to(device)
                if sample_rate != 16000:
                    if sample_rate not in self._resample_buffer:
                        self._resample_buffer[sample_rate] = torchaudio.transforms.Resample(
                            orig_freq=sample_rate, new_freq=16000
                        )  # .to(device)
                    # self._resample_buffer[sample_rate].to(device)
                    audio = self._resample_buffer[sample_rate](audio)
                # if audio.shape[0] > 1:
                #     audio = audio[:1]
                # audio = audio[0]
                if audio.dim() == 2:
                    audio = audio.mean(0)
                audio = audio.cpu().numpy()
                time_step = 0
                while time_step * 16000 < audio.shape[0]:
                    audio_segment = audio[time_step * 16000 : (time_step + 30) * 16000]
                    audios.append(audio_segment)
                    indices.append(idx)
                    time_step += 30

            if len(audios) == 0:
                return [0]

            pooling_kernel_size = model.config.pooling_kernel_size or 1
            stride = model.conv1.stride[0] * model.conv2.stride[0] * pooling_kernel_size * feature_extractor.hop_length
            all_speech_tokens = [[] for _ in range(len(utts))]
            batch_size = 32
            for start in range(0, len(audios), batch_size):
                features = feature_extractor(
                    audios[start : start + batch_size],
                    sampling_rate=16000,
                    return_attention_mask=True,
                    return_tensors="pt",
                    device=device,
                    padding="longest",
                    pad_to_multiple_of=stride,
                )
                features = features.to(device=device)
                outputs = model(**features)
                speech_tokens = outputs.quantized_token_ids
                attention_mask = features.attention_mask[:, :: model.conv1.stride[0] * model.conv2.stride[0]]
                attention_mask = attention_mask[:, :: model.config.pooling_kernel_size]
                assert attention_mask.shape == speech_tokens.shape
                for i in range(len(speech_tokens)):
                    idx = indices[start + i]
                    speech_token = speech_tokens[i][attention_mask[i].bool()].tolist()
                    all_speech_tokens[idx].extend(speech_token)

            return all_speech_tokens


class WavFrontendTokenizer:
    def __init__(
        self,
    ):
        self.sample_rate = 16000

        self.is_discrete = True
        self.is_contiguous = True

        self._resample_buffer: dict[int, torchaudio.transforms.Resample] = {}

        self.tokenizer_type = "wav_frontend"

    def load_model(self):
        if hasattr(self, "frontend"):
            return

        self.device = "cpu"

        logger.info(f"⏳ {self.device=} Loading {self.tokenizer_type}")
        self.frontend = WavFrontend(
            fs=16000,
            window="hamming",
            n_mels=80,
            frame_length=25,
            frame_shift=10,
            lfr_m=7,
            lfr_n=6,
            cmvn_file=None,
        )
        logger.info(f"⏳ {self.device=} Loading {self.tokenizer_type} Done")

    @torch.no_grad()
    def encode(self, audio_or_path, **kwargs):
        if not hasattr(self, "frontend"):
            self.load_model()

        if isinstance(audio_or_path, tuple):
            audio, sample_rate = audio_or_path
        else:
            audio, sample_rate = torchaudio.load(audio_or_path)
        # print(f"{audio.size()=} {sample_rate=}")
        if audio.dim() == 2:
            audio = audio.mean(0)

        if sample_rate != self.sample_rate:
            if sample_rate not in self._resample_buffer:
                # print(f"torchaudio.transforms.Resample {sample_rate=} {self.sample_rate=} {self.device=}", flush=True)
                self._resample_buffer[sample_rate] = torchaudio.transforms.Resample(
                    orig_freq=sample_rate, new_freq=self.sample_rate
                ).to(self.device)
            audio = audio.to(self.device)
            self._resample_buffer[sample_rate].to(self.device)
            audio = self._resample_buffer[sample_rate](audio[None, :])[0, :]
            audio = audio.cpu()
        # resampler = torchaudio.transforms.Resample(
        #     orig_freq=sample_rate, new_freq=self.sample_rate
        # )
        # audio = resampler(audio[None, :])[0, :]
        # audio = audio.to(self.device)

        speech, speech_lengths = extract_fbank(audio, data_type="sound", frontend=self.frontend)

        speech = speech[0]
        # print(f"{audio.size()=}")
        # print(f"{speech_lengths=}")
        # print(f"{speech.size()=}")

        # if max(speech_lengths) > 512:
        #     raise Exception(f"Audio is to long {speech_lengths}")

        speech = torch.nan_to_num(speech, nan=0, posinf=0, neginf=0)

        return {
            "audio": speech,
            "audio_token_length_func": len,
            "duration_seconds": len(audio) / self.sample_rate,
        }

    @torch.no_grad()
    def decode(self, audio_tokens, **kwargs):
        return None


class VisionTokenizer:
    def __init__(self, tokenizer_contiguous=None, tokenizer_discrete=None):
        self.tokenizer_contiguous = tokenizer_contiguous
        self.tokenizer_discrete = tokenizer_discrete

        # if tokenizer_contiguous is not None:
        #     self.is_contiguous = True
        # else:
        #     self.is_contiguous = False
        self.is_contiguous = True

        if tokenizer_discrete is not None:
            self.is_discrete = True
        else:
            self.is_discrete = False

        logger.info(f"{self.first_vision_token=}")
        logger.info(f"{self.last_vision_token=}")

    @property
    def first_vision_token(self):
        if self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.first_vision_token
        else:
            return None

    @property
    def last_vision_token(self):
        if self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.last_vision_token
        else:
            return None

    def load_model(self):
        if hasattr(self.tokenizer_contiguous, "load_model") and callable(
            getattr(self.tokenizer_contiguous, "load_model")
        ):
            self.tokenizer_contiguous.load_model()

        if hasattr(self.tokenizer_discrete, "load_model") and callable(getattr(self.tokenizer_discrete, "load_model")):
            self.tokenizer_discrete.load_model()

    @torch.no_grad()
    def encode(self, audio_or_path, is_discrete=False, is_contiguous=True, **kwargs):
        if is_discrete and self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.encode(audio_or_path, **kwargs)

        if is_contiguous and self.tokenizer_contiguous is not None:
            return self.tokenizer_contiguous.encode(audio_or_path, **kwargs)

        return None

    @torch.no_grad()
    def decode(self, audio_tokens, **kwargs):
        if self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.decode(audio_tokens, **kwargs)

        return None


class AudioTokenizer:
    def __init__(self, tokenizer_contiguous=None, tokenizer_discrete=None):
        self.tokenizer_contiguous = tokenizer_contiguous
        self.tokenizer_discrete = tokenizer_discrete

        if tokenizer_contiguous is not None:
            self.is_contiguous = True
        else:
            self.is_contiguous = False

        if tokenizer_discrete is not None:
            self.is_discrete = True
        else:
            self.is_discrete = False

        logger.info(f"{self.first_audio_token=}")
        logger.info(f"{self.last_audio_token=}")

    @property
    def first_audio_token(self):
        if self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.first_audio_token
        else:
            return None

    @property
    def last_audio_token(self):
        if self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.last_audio_token
        else:
            return None

    @property
    def num_codebook(self):
        if self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.num_codebook
        else:
            return 0

    def load_model(self):
        if hasattr(self.tokenizer_contiguous, "load_model") and callable(
            getattr(self.tokenizer_contiguous, "load_model")
        ):
            self.tokenizer_contiguous.load_model()

        if hasattr(self.tokenizer_discrete, "load_model") and callable(getattr(self.tokenizer_discrete, "load_model")):
            self.tokenizer_discrete.load_model()

    @torch.no_grad()
    def encode(self, audio_or_path, is_discrete=False, is_contiguous=True, **kwargs):
        if is_discrete and self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.encode(audio_or_path, **kwargs)

        if is_contiguous and self.tokenizer_contiguous is not None:
            return self.tokenizer_contiguous.encode(audio_or_path, **kwargs)

        return None

    @torch.no_grad()
    def decode(self, audio_tokens, **kwargs):
        if self.tokenizer_discrete is not None:
            return self.tokenizer_discrete.decode(audio_tokens, **kwargs)

        return None
