#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/youtu_vita/modular_youtu_vita.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_youtu_vita.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the Tencent and HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import mimetypes
import os
import time

import decord
import ffmpeg
import numpy as np
import PIL.Image
import torch
import torchaudio

from ...video_processing_utils import BaseVideoProcessor
from .modeling_youtu_vita import Youtu_VITA_TOKEN
from .processing_youtu_vita import YoutuVITAVideosKwargs


# _GLOBAL_TOKEN = Qwen3_VITA_TOKEN()
_GLOBAL_TOKEN = Youtu_VITA_TOKEN()


def get_token():
    _ensure_var_is_initialized(_GLOBAL_TOKEN, "token")
    return _GLOBAL_TOKEN


def _ensure_var_is_initialized(var, name):
    """Make sure the input variable is not None."""
    assert var is not None, f"{name} is not initialized."


def has_audio(video_path):
    if not isinstance(video_path, str):
        return False

    if os.path.isdir(video_path):
        return False

    try:
        # Probe for audio streams only
        probe_result = ffmpeg.probe(video_path, select_streams="a")
        # If 'streams' list is not empty, it indicates an audio stream exists
        return bool(probe_result["streams"])
    except ffmpeg.Error as e:
        print(f"Error probing video: {e.stderr.decode()}", flush=True)
        return False


class YoutuVITAVideoProcessor(BaseVideoProcessor):
    model_input_names = ["pixel_values", "image_grid_thw"]
    valid_kwargs = YoutuVITAVideosKwargs

    def __init__(
        self,
        image_processor=None,
        audio_processor=None,
        resolution_type=None,
        min_num_tokens=64,
        max_num_tokens=8192,
        image_min_num_tokens=4,
        image_max_num_tokens=256,
        temporal_patch_size=1,
        spatial_merge_size=2,
        patch_size=14,
        video_key_frame=False,
        **kwargs,
    ) -> None:
        super().__init__(**kwargs)

        self.image_processor = image_processor
        self.audio_processor = audio_processor

        self.resolution_type = resolution_type
        self.temporal_patch_size = temporal_patch_size
        self.spatial_merge_size = spatial_merge_size
        self.patch_size = patch_size
        self.max_num_tokens = max_num_tokens
        self.min_num_tokens = min_num_tokens
        self.image_max_num_tokens = image_max_num_tokens
        self.image_min_num_tokens = image_min_num_tokens

        self.sample_rate = 16000

        self.video_key_frame = video_key_frame

    def to_dict(self):
        output = super().to_dict()
        # Remove the non-serializable object before returning
        if "image_processor" in output:
            del output["image_processor"]
        if "audio_processor" in output:
            del output["audio_processor"]
        return output

    def get_frame_paths(self, frame_root, num_frames=8):
        os.makedirs(frame_root, exist_ok=True)

        self.frame_tmpl = "frame-{}-of-{}.jpg"
        return [os.path.join(frame_root, self.frame_tmpl.format(i, num_frames)) for i in range(1, num_frames + 1)]

    def save_video_frames(self, vid_path, max_fps=1, num_frames=8):
        vid = decord.VideoReader(vid_path, num_threads=1)

        # step_size = len(vid) / (num_frames + 1)
        step_size = len(vid) / num_frames

        # step_size = max(1, step_size)
        fps = vid.get_avg_fps()
        fps = round(fps)
        step_size = max(fps / max_fps, step_size)

        # indices = [int(i * step_size) for i in range(1, num_frames + 1)]
        indices = [int(i * step_size) for i in range(0, num_frames)]
        indices = [i for i in indices if i < len(vid)]

        num_frames = len(indices)

        frame_paths = self.get_frame_paths(vid_path + ".saved_frames", num_frames)
        flag = np.all([os.path.exists(p) for p in frame_paths])
        if flag:
            return frame_paths

        images = [vid[i].asnumpy() for i in indices]
        images = [PIL.Image.fromarray(arr) for arr in images]

        for im, pth in zip(images, frame_paths):
            # if not os.path.exists(pth):
            #     im.save(pth)
            im.save(pth)
        # print(f"save_video_frames vid_path {vid_path} fps {fps} len(vid) {len(vid)} frame_paths {frame_paths}")
        return frame_paths

    def get_video_frames(self, vid_path, max_fps=1, num_frames=8):
        vid = decord.VideoReader(vid_path, num_threads=1)

        fps = vid.get_avg_fps()
        fps = round(fps)

        if self.video_key_frame:
            indices = get_video_keyframe(vid_path)
            # TODO: fix this
            sample_fps = None
            sample_fps = 1
            if len(indices) > num_frames:
                random_indices = sorted(random.sample(range(len(indices)), num_frames))
                indices = [indices[i] for i in random_indices]
        else:
            # step_size = len(vid) / (num_frames + 1)
            step_size = len(vid) / num_frames
            step_size = max(fps / max_fps, step_size)

            # indices = [int(i * step_size) for i in range(1, num_frames + 1)]
            indices = [int(i * step_size) for i in range(0, num_frames)]
            sample_fps = 1 / (step_size / fps)

        indices = [i for i in indices if i < len(vid)]

        images = [vid[i].asnumpy() for i in indices]
        images = [PIL.Image.fromarray(arr) for arr in images]

        timestamps = [1.0 / fps * i for i in indices]

        duration_seconds = len(vid) / vid.get_avg_fps()

        # print(f"get_video_frames vid_path {vid_path} fps {fps} len(vid) {len(vid)} frame_paths {frame_paths}")
        return images, sample_fps, timestamps, duration_seconds

    def get_image_and_audio(self, video_file_or_dir, max_num_frames=8, max_fps=1):
        if isinstance(video_file_or_dir, str) and os.path.isfile(video_file_or_dir):
            mime_type, _ = mimetypes.guess_type(video_file_or_dir)
        else:
            mime_type = None

        if mime_type is None:
            mime_type = "video/"

        if isinstance(video_file_or_dir, PIL.Image.Image):
            img_or_path_list = [
                video_file_or_dir,
            ]
            fps = 1
            timestamps = [1 / fps * i for i in range(len(img_or_path_list))]
            duration_seconds = len(img_or_path_list) / fps

        elif os.path.isfile(video_file_or_dir) and mime_type.startswith("image/"):
            img_or_path_list = [PIL.Image.open(x).convert("RGB") for x in [video_file_or_dir]]
            fps = 1
            timestamps = [1 / fps * i for i in range(len(img_or_path_list))]
            duration_seconds = len(img_or_path_list) / fps

        elif os.path.isfile(video_file_or_dir) and mime_type.startswith("video/"):
            # frame_paths = self.save_video_frames(
            #     video_file_or_dir, num_frames=max_num_frames, max_fps=max_fps
            # )
            # img_or_path_list = frame_paths
            img_or_path_list, fps, timestamps, duration_seconds = self.get_video_frames(
                video_file_or_dir, num_frames=max_num_frames, max_fps=max_fps
            )

        elif os.path.isdir(video_file_or_dir):
            all_filepath = []
            for root, dirs, files in os.walk(video_file_or_dir):
                for filename in files:
                    if filename.endswith("png") or filename.endswith("jpeg") or filename.endswith("jpg"):
                        filepath = os.path.join(root, filename)
                        all_filepath.append(filepath)

            if len(all_filepath) == 0:
                return None

            # all_filepath.sort()
            all_filepath = natsort.natsorted(all_filepath)
            total_frames = len(all_filepath)
            if "ShareGPTVideo" in video_file_or_dir:
                fps = 2
            else:
                fps = 1
            target_frame = int(min(total_frames / fps * max_fps, max_num_frames))
            index = [int(1.0 * total_frames / target_frame) * x for x in range(target_frame)]

            selected_filepath = [all_filepath[x] for x in index]

            img_or_path_list = selected_filepath

            fps = target_frame / total_frames * fps
            second_per_frame = [1.0 / fps] * len(img_or_path_list)
            timestamps = [1.0 / fps * i for i in range(len(img_or_path_list))]

            duration_seconds = total_frames / fps

        else:
            # print(f"FileNotFoundError {video_file_or_dir}")
            if isinstance(video_file_or_dir, str):
                raise FileNotFoundError(video_file_or_dir)
            else:
                raise NotImplementedError(video_file_or_dir)

        audio = None
        # if has_audio_track(video_file_or_dir):
        if has_audio(video_file_or_dir):
            audio, sample_rate = torchaudio.load(video_file_or_dir)
            # print(f"{audio.size()=} {sample_rate=}")
            if audio.dim() == 2:
                audio = audio.mean(0)

            if sample_rate != self.sample_rate:
                resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=self.sample_rate)
                audio = resampler(audio[None, :])[0, :]

        return img_or_path_list, fps, timestamps, (audio, self.sample_rate), duration_seconds

    def process_video(self, video_file_or_dir, max_num_frames=8, max_fps=1):
        images, fps, timestamps, (audio, sample_rate), duration_seconds = self.get_image_and_audio(
            video_file_or_dir,
            max_num_frames=max_num_frames,
            max_fps=max_fps,
        )

        if self.resolution_type == "native":
            min_pixels = (self.patch_size * self.spatial_merge_size) ** 2 * self.min_num_tokens // len(images)
            max_pixels = (self.patch_size * self.spatial_merge_size) ** 2 * self.max_num_tokens // len(images)

            image_min_pixels = (self.patch_size * self.spatial_merge_size) ** 2 * self.image_min_num_tokens
            image_max_pixels = (self.patch_size * self.spatial_merge_size) ** 2 * self.image_max_num_tokens

            min_pixels = max(min_pixels, image_min_pixels)
            max_pixels = min(max_pixels, image_max_pixels)

            # print(f"{len(images)=} {min_pixels=} {max_pixels=}")
            image_data = self.image_processor.process_images(
                images,
                is_contiguous=True,
                resolution_type=self.resolution_type,
                min_pixels=min_pixels,
                max_pixels=max_pixels,
            )
            image_frames = image_data["images"]
            best_height = image_data["image_height"]
            best_width = image_data["image_width"]
        else:
            image_data = self.image_processor.process_images_to_tensor(images)
            image_frames = image_data["images"]
            best_height = image_data["image_height"]
            best_width = image_data["image_width"]

        if audio is not None:
            total_time = len(audio) / sample_rate
            # print(f"{duration_seconds=} {total_time=}", flush=True)

            audio_dict = self.audio_processor.process_audio(
                (audio, sample_rate), is_discrete=False, is_contiguous=True
            )
            audio = audio_dict["audio"]
            audio_token_length_func = audio_dict["audio_token_length_func"]

            # audio_frames = torch.chunk(audio, chunks=len(image_frames), dim=0)
            full_timestamps = timestamps + [total_time]
            audio_frames = []
            for split_idx in range(len(image_frames)):
                st = full_timestamps[split_idx]
                ed = full_timestamps[split_idx + 1]

                st = int(st / total_time * len(audio))
                ed = int(ed / total_time * len(audio))

                audio_frame = audio[st:ed]
                audio_frames.append(audio_frame)

        else:
            audio_frames = None
            audio_token_length_func = None

        # grid_t = image_frames.size(1) // self.temporal_patch_size
        grid_t = 1 // self.temporal_patch_size
        grid_h = best_height // self.patch_size
        grid_w = best_width // self.patch_size

        video_grid_thw = [[grid_t, grid_h, grid_w]]
        video_grid_thw = video_grid_thw * image_frames.size(0)

        if fps is not None:
            second_per_grids = [1.0 / fps] * image_frames.size(0)
        else:
            second_per_grids = None

        # print(f"{image_frames.size()=} {video_grid_thw=} {max_fps=} {max_num_frames=} {fps=} {second_per_grids=} ")

        return (
            image_frames,
            audio_frames,
            audio_token_length_func,
            video_grid_thw,
            second_per_grids,
            timestamps,
            duration_seconds,
        )

    def process_video_raw(self, video_file_or_dir, max_num_frames=8, max_fps=1, use_audio_in_video=True):
        images, fps, timestamps, (audio, sample_rate) = self.get_image_and_audio(
            video_file_or_dir,
            max_num_frames=max_num_frames,
            max_fps=max_fps,
            use_audio_in_video=use_audio_in_video,
        )

        image_frames = images

        if audio is not None:
            total_time = len(audio) / sample_rate

            # audio_frames = torch.chunk(audio, chunks=len(image_frames), dim=0)
            full_timestamps = timestamps + [total_time]
            audio_frames = []
            for split_idx in range(len(image_frames)):
                st = full_timestamps[split_idx]
                ed = full_timestamps[split_idx + 1]

                st = int(st / total_time * len(audio))
                ed = int(ed / total_time * len(audio))

                audio_frame = audio[st:ed]
                audio_frames.append(audio_frame)

        else:
            audio_frames = None

        # grid_t = image_frames.size(1) // self.temporal_patch_size
        grid_t = 1 // self.temporal_patch_size
        grid_h = self.image_processor.tile_image_size // self.patch_size
        grid_w = self.image_processor.tile_image_size // self.patch_size

        video_grid_thw = [[grid_t, grid_h, grid_w]]
        video_grid_thw = video_grid_thw * len(image_frames)

        if fps is not None:
            second_per_grids = [1.0 / fps] * len(image_frames)
        else:
            second_per_grids = None

        # print(f"{len(image_frames)=} {video_grid_thw=} {max_fps=} {max_num_frames=} {fps=} {second_per_grids=} ")

        return image_frames, audio_frames, video_grid_thw, second_per_grids, timestamps

    def add_video_input_contiguous(
        self,
        input_ids,
        video_paths,
        tokenizer,
        targets=None,
        is_pretrain=False,
        max_num_frames=4096,
        max_fps=1,
        use_audio_in_video=True,
        use_vision_in_video=True,
        video_audio_chunk_min_second=2,
        video_audio_chunk_max_second=30,
        **kwargs,
    ):
        GLOBAL_TOKEN = get_token()

        IMG_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.IMG_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        IMG_START_ID = tokenizer(GLOBAL_TOKEN.IMG_START_TOKEN, add_special_tokens=False).input_ids
        IMG_END_ID = tokenizer(GLOBAL_TOKEN.IMG_END_TOKEN, add_special_tokens=False).input_ids

        AUD_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.AUD_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        AUD_START_ID = tokenizer(GLOBAL_TOKEN.AUD_START_TOKEN, add_special_tokens=False).input_ids
        AUD_END_ID = tokenizer(GLOBAL_TOKEN.AUD_END_TOKEN, add_special_tokens=False).input_ids

        VID_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.VID_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        VID_START_ID = tokenizer(GLOBAL_TOKEN.VID_START_TOKEN, add_special_tokens=False).input_ids
        VID_END_ID = tokenizer(GLOBAL_TOKEN.VID_END_TOKEN, add_special_tokens=False).input_ids

        PATCH_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.PATCH_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        PATCH_START_ID = tokenizer(GLOBAL_TOKEN.PATCH_START_TOKEN, add_special_tokens=False).input_ids
        PATCH_END_ID = tokenizer(GLOBAL_TOKEN.PATCH_END_TOKEN, add_special_tokens=False).input_ids

        IMG_TAG_ID = tokenizer(GLOBAL_TOKEN.IMG_TAG_TOKEN, add_special_tokens=False).input_ids
        AUD_TAG_ID = tokenizer(GLOBAL_TOKEN.AUD_TAG_TOKEN, add_special_tokens=False).input_ids
        VID_TAG_ID = tokenizer(GLOBAL_TOKEN.VID_TAG_TOKEN, add_special_tokens=False).input_ids

        assert len(IMG_CONTEXT_ID) == 1
        assert len(IMG_START_ID) == 1
        assert len(IMG_END_ID) == 1

        assert len(AUD_CONTEXT_ID) == 1
        assert len(AUD_START_ID) == 1
        assert len(AUD_END_ID) == 1

        assert len(VID_CONTEXT_ID) == 1
        assert len(VID_START_ID) == 1
        assert len(VID_END_ID) == 1

        assert len(PATCH_CONTEXT_ID) == 1
        assert len(PATCH_START_ID) == 1
        assert len(PATCH_END_ID) == 1

        IMG_CONTEXT_ID = IMG_CONTEXT_ID[0]
        IMG_START_ID = IMG_START_ID[0]
        IMG_END_ID = IMG_END_ID[0]

        AUD_CONTEXT_ID = AUD_CONTEXT_ID[0]
        AUD_START_ID = AUD_START_ID[0]
        AUD_END_ID = AUD_END_ID[0]

        VID_CONTEXT_ID = VID_CONTEXT_ID[0]
        VID_START_ID = VID_START_ID[0]
        VID_END_ID = VID_END_ID[0]

        PATCH_CONTEXT_ID = PATCH_CONTEXT_ID[0]
        PATCH_START_ID = PATCH_START_ID[0]
        PATCH_END_ID = PATCH_END_ID[0]

        IMG_TAG_ID = IMG_TAG_ID[0]
        AUD_TAG_ID = AUD_TAG_ID[0]
        VID_TAG_ID = VID_TAG_ID[0]

        nl_tokens = tokenizer("\n", add_special_tokens=False).input_ids

        vid_positions = [i for i, x in enumerate(input_ids) if x == VID_TAG_ID]
        assert len(vid_positions) == len(video_paths), video_paths

        images = []
        image_indices = []
        audios = []
        audio_indices = []
        video_grid_thw = []
        second_per_grids = []

        new_input_ids = []
        new_targets = []
        st = 0
        for vid_idx, vid_pos in enumerate(vid_positions):
            (
                image_frames,
                audio_frames,
                audio_token_length_func,
                _video_grid_thw,
                _second_per_grids,
                second_frames,
                duration_seconds,
            ) = self.process_video(video_paths[vid_idx], max_num_frames, max_fps)

            if audio_frames is not None:
                # print(f"{len(image_frames)=} {len(audio_frames)=}")
                # print(f"{[x.size() for x in image_frames]=}")
                # print(f"{[x.size() for x in audio_frames]=}")

                num_frames = min(len(image_frames), len(audio_frames))
                image_frames = image_frames[:num_frames]
                audio_frames = audio_frames[:num_frames]

            new_input_ids += input_ids[st:vid_pos]
            if targets is not None:
                new_targets += targets[st:vid_pos]

            if audio_frames is not None:
                second_per_audio = 1.0 * duration_seconds / sum([len(x) for x in audio_frames])

                image_chunks = []
                image_second_chunks = []
                audio_chunks = []
                audio_second_chunks = []

                image_chunk = []
                image_second_chunk = []
                audio_chunk = []
                audio_second_chunk = []
                for image_frame, audio_frame, second_frame in zip(image_frames, audio_frames, second_frames):
                    audio_second = len(audio_frame) * second_per_audio
                    audio_chunk_second = sum([len(x) * second_per_audio for x in audio_chunk])

                    if audio_second + audio_chunk_second < video_audio_chunk_min_second:
                        image_chunk.append(image_frame)
                        image_second_chunk.append(second_frame)

                        audio_chunk.append(audio_frame)
                        audio_second_chunk.append(second_frame)

                    elif audio_second + audio_chunk_second <= video_audio_chunk_max_second:
                        image_chunk.append(image_frame)
                        image_second_chunk.append(second_frame)

                        audio_chunk.append(audio_frame)
                        audio_second_chunk.append(second_frame)

                        image_chunks.append(image_chunk)
                        image_second_chunks.append(image_second_chunk)

                        audio_chunk = [torch.cat(audio_chunk, dim=0)]
                        audio_second_chunk = [audio_second_chunk[0]]
                        audio_chunks.append(audio_chunk)
                        audio_second_chunks.append(audio_second_chunk)

                        image_chunk = []
                        image_second_chunk = []

                        audio_chunk = []
                        audio_second_chunk = []

                    elif audio_second + audio_chunk_second > video_audio_chunk_max_second:
                        assert audio_chunk_second == 0

                        image_chunk.append(image_frame)
                        image_second_chunk.append(second_frame)

                        audio_chunk_size = int(video_audio_chunk_max_second / second_per_audio)
                        audio_chunk = torch.split(audio_frame, audio_chunk_size)
                        cur_second = second_frame
                        for x in audio_chunk:
                            audio_second_chunk.append(cur_second)
                            cur_second += len(x) * second_per_audio

                        image_chunks.append(image_chunk)
                        image_second_chunks.append(image_second_chunk)

                        audio_chunks.append(audio_chunk)
                        audio_second_chunks.append(audio_second_chunk)

                        image_chunk = []
                        image_second_chunk = []

                        audio_chunk = []
                        audio_second_chunk = []

                if len(image_chunk) > 0:
                    image_chunks.append(image_chunk)
                    image_second_chunks.append(image_second_chunk)

                    audio_chunk = [torch.cat(audio_chunk, dim=0)]
                    audio_second_chunk = [audio_second_chunk[0]]
                    audio_chunks.append(audio_chunk)
                    audio_second_chunks.append(audio_second_chunk)

            else:
                image_chunks = [image_frames]
                image_second_chunks = [second_frames]
                audio_chunks = [[]]
                audio_second_chunks = [[]]

            assert len(image_frames) == sum([len(x) for x in image_chunks])
            # assert len(audio_frames) == sum([len(x) for x in audio_chunks])

            if use_vision_in_video:
                if self.image_processor.resolution_type == "native":
                    images.append(
                        torch.cat(
                            [
                                self.image_processor.convert_image_to_patches_with_pixel_shuffle(x)
                                for x in image_frames
                            ],
                            dim=0,
                        )
                    )

                else:
                    images.append(image_frames)

            if use_audio_in_video and audio_frames is not None:
                # audios.extend(audio_frames)
                audios.extend([xx for x in audio_chunks for xx in x])

            for (
                image_chunk_frames,
                image_second_chunk_frames,
                audio_chunk_frames,
                audio_second_chunk_frames,
            ) in zip(
                image_chunks,
                image_second_chunks,
                audio_chunks,
                audio_second_chunks,
            ):
                if not use_vision_in_video:
                    image_chunk_frames = []
                    image_second_chunk_frames = []
                if not use_audio_in_video:
                    audio_chunk_frames = []
                    audio_second_chunk_frames = []

                for image_chunk_frame, image_second_chunk_frame in zip(image_chunk_frames, image_second_chunk_frames):
                    # add timestamp
                    timestamp = time.strftime("%H:%M:%S", time.gmtime(round(image_second_chunk_frame)))
                    _input_id = tokenizer(timestamp, add_special_tokens=False).input_ids
                    _target = [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(_input_id)
                    new_input_ids += _input_id
                    if targets is not None:
                        new_targets += _target

                    new_input_ids += [VID_START_ID]
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                    image_token_length = (
                        _video_grid_thw[0][0]
                        * _video_grid_thw[0][1]
                        * _video_grid_thw[0][2]
                        // self.spatial_merge_size
                        // self.spatial_merge_size
                    )
                    image_indice_b = torch.zeros(
                        1, image_token_length, dtype=torch.int64
                    )  # This will change in collate_fn
                    image_indice_s = (
                        torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                        .unsqueeze(0)
                        .repeat(1, 1)
                    )
                    image_indice_b_s = torch.stack(
                        [image_indice_b, image_indice_s], dim=0
                    )  # 2, num_image, image_length
                    if self.image_processor.resolution_type == "native":
                        image_indices.append(image_indice_b_s.view(2, -1))
                    else:
                        image_indices.append(image_indice_b_s)

                    new_input_ids += [VID_CONTEXT_ID] * image_token_length
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                    new_input_ids += [VID_END_ID]
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                for audio_chunk_frame, audio_second_chunk_frame in zip(audio_chunk_frames, audio_second_chunk_frames):
                    # add timestamp
                    timestamp = time.strftime("%H:%M:%S", time.gmtime(round(audio_second_chunk_frame)))
                    _input_id = tokenizer(timestamp, add_special_tokens=False).input_ids
                    _target = [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(_input_id)
                    new_input_ids += _input_id
                    if targets is not None:
                        new_targets += _target

                    new_input_ids += [AUD_START_ID]
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                    # audio_token_length = audio_chunk_frame.size(0)
                    # audio_token_length = audio_token_length_func(audio_chunk_frame.size(0))
                    audio_token_length = audio_token_length_func(audio_chunk_frame)
                    audio_indice_b = torch.zeros(
                        1, audio_token_length, dtype=torch.int64
                    )  # This will change in collate_fn
                    audio_indice_s = (
                        torch.arange(len(new_input_ids), len(new_input_ids) + audio_token_length)
                        .unsqueeze(0)
                        .repeat(1, 1)
                    )
                    audio_indice_b_s = torch.stack(
                        [audio_indice_b, audio_indice_s], dim=0
                    )  # 2, num_audio, audio_length
                    audio_indices.append(audio_indice_b_s)

                    new_input_ids += [AUD_CONTEXT_ID] * audio_token_length
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * audio_token_length

                    new_input_ids += [AUD_END_ID]
                    if targets is not None:
                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            video_grid_thw.extend(_video_grid_thw)
            second_per_grids.extend(_second_per_grids)

            st = vid_pos + 1

        new_input_ids += input_ids[st:]
        if targets is not None:
            new_targets += targets[st:]

        input_ids = new_input_ids
        if targets is not None:
            targets = new_targets

        video_grid_thw = torch.tensor(video_grid_thw, dtype=torch.long)
        second_per_grids = torch.tensor(second_per_grids, dtype=torch.long)

        if targets is not None:
            return (
                input_ids,
                images,
                image_indices,
                audios,
                audio_indices,
                video_grid_thw,
                second_per_grids,
                targets,
            )

        if len(images) == 0:
            images = None
            image_indices = None

        else:
            images = torch.cat(images, dim=0)
            image_indices = torch.cat(image_indices, dim=1)

            image_indices = image_indices.contiguous().to(torch.cuda.current_device())
            if True:
                images = torch.tensor(images, dtype=torch.bfloat16).contiguous().to(torch.cuda.current_device())

            else:
                images = torch.tensor(images, dtype=torch.float16).contiguous().to(torch.cuda.current_device())

        if len(audios) == 0:
            audios = None
            audio_indices = None

        return (
            input_ids,
            images,
            image_indices,
            audios,
            audio_indices,
            video_grid_thw,
            second_per_grids,
        )

    def add_video_input_discrete_and_contiguous(
        self,
        input_ids,
        video_paths,
        tokenizer,
        targets=None,
        is_pretrain=False,
        image_token_length=256,
        max_num_frames=4096,
        max_fps=1,
        use_audio_in_video=True,
        video_chunk_size=2,
        video_audio_chunk_size=None,
        video_audio_num_subchunk=None,
        **kwargs,
    ):
        GLOBAL_TOKEN = get_token()

        IMG_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.IMG_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        IMG_START_ID = tokenizer(GLOBAL_TOKEN.IMG_START_TOKEN, add_special_tokens=False).input_ids
        IMG_END_ID = tokenizer(GLOBAL_TOKEN.IMG_END_TOKEN, add_special_tokens=False).input_ids

        AUD_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.AUD_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        AUD_START_ID = tokenizer(GLOBAL_TOKEN.AUD_START_TOKEN, add_special_tokens=False).input_ids
        AUD_END_ID = tokenizer(GLOBAL_TOKEN.AUD_END_TOKEN, add_special_tokens=False).input_ids

        VID_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.VID_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        VID_START_ID = tokenizer(GLOBAL_TOKEN.VID_START_TOKEN, add_special_tokens=False).input_ids
        VID_END_ID = tokenizer(GLOBAL_TOKEN.VID_END_TOKEN, add_special_tokens=False).input_ids

        PATCH_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.PATCH_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        PATCH_START_ID = tokenizer(GLOBAL_TOKEN.PATCH_START_TOKEN, add_special_tokens=False).input_ids
        PATCH_END_ID = tokenizer(GLOBAL_TOKEN.PATCH_END_TOKEN, add_special_tokens=False).input_ids

        IMG_TAG_ID = tokenizer(GLOBAL_TOKEN.IMG_TAG_TOKEN, add_special_tokens=False).input_ids
        AUD_TAG_ID = tokenizer(GLOBAL_TOKEN.AUD_TAG_TOKEN, add_special_tokens=False).input_ids
        VID_TAG_ID = tokenizer(GLOBAL_TOKEN.VID_TAG_TOKEN, add_special_tokens=False).input_ids

        assert len(IMG_CONTEXT_ID) == 1
        assert len(IMG_START_ID) == 1
        assert len(IMG_END_ID) == 1

        assert len(AUD_CONTEXT_ID) == 1
        assert len(AUD_START_ID) == 1
        assert len(AUD_END_ID) == 1

        assert len(VID_CONTEXT_ID) == 1
        assert len(VID_START_ID) == 1
        assert len(VID_END_ID) == 1

        assert len(PATCH_CONTEXT_ID) == 1
        assert len(PATCH_START_ID) == 1
        assert len(PATCH_END_ID) == 1

        IMG_CONTEXT_ID = IMG_CONTEXT_ID[0]
        IMG_START_ID = IMG_START_ID[0]
        IMG_END_ID = IMG_END_ID[0]

        AUD_CONTEXT_ID = AUD_CONTEXT_ID[0]
        AUD_START_ID = AUD_START_ID[0]
        AUD_END_ID = AUD_END_ID[0]

        VID_CONTEXT_ID = VID_CONTEXT_ID[0]
        VID_START_ID = VID_START_ID[0]
        VID_END_ID = VID_END_ID[0]

        PATCH_CONTEXT_ID = PATCH_CONTEXT_ID[0]
        PATCH_START_ID = PATCH_START_ID[0]
        PATCH_END_ID = PATCH_END_ID[0]

        IMG_TAG_ID = IMG_TAG_ID[0]
        AUD_TAG_ID = AUD_TAG_ID[0]
        VID_TAG_ID = VID_TAG_ID[0]

        nl_tokens = tokenizer("\n", add_special_tokens=False).input_ids

        vid_positions = [i for i, x in enumerate(input_ids) if x == VID_TAG_ID]
        assert len(vid_positions) == len(video_paths), video_paths

        images = []
        image_indices = []
        audios = []
        audio_indices = []
        video_grid_thw = []
        second_per_grids = []

        new_input_ids = []
        new_targets = []
        st = 0
        for vid_idx, vid_pos in enumerate(vid_positions):
            (
                image_frames,
                audio_frames,
                _video_grid_thw,
                _second_per_grids,
                second_frames,
            ) = self.process_video_raw(
                video_paths[vid_idx], max_num_frames, max_fps, use_audio_in_video=use_audio_in_video
            )

            if audio_frames is not None:
                # print(f"{len(image_frames)=} {len(audio_frames)=}")
                # print(f"{[x.size() for x in image_frames]=}")
                # print(f"{[x.size() for x in audio_frames]=}")

                num_frames = min(len(image_frames), len(audio_frames))
                image_frames = image_frames[:num_frames]
                audio_frames = audio_frames[:num_frames]

            new_input_ids += input_ids[st:vid_pos]
            if targets is not None:
                new_targets += targets[st:vid_pos]

            second_chunks = [
                second_frames[i : i + video_chunk_size] for i in range(0, len(second_frames), video_chunk_size)
            ]

            image_chunks = [
                image_frames[i : i + video_chunk_size] for i in range(0, len(image_frames), video_chunk_size)
            ]
            if audio_frames is not None:
                audio_chunks = [
                    audio_frames[i : i + video_chunk_size] for i in range(0, len(audio_frames), video_chunk_size)
                ]
            else:
                audio_chunks = [[] for i in range(0, len(image_frames), video_chunk_size)]

            # resplit audio frame
            if audio_frames is not None:
                if video_audio_chunk_size is not None:
                    audio_chunks = [torch.cat(x, dim=0) for x in audio_chunks]
                    audio_chunks = [torch.split(x, video_audio_chunk_size, dim=0) for x in audio_chunks]

                if video_audio_num_subchunk is not None:
                    audio_chunks = [x[:video_audio_num_subchunk] for x in audio_chunks]
            # print([[xx.size() for xx in x] for x in audio_chunks])

            images.extend(image_frames)
            if audio_frames is not None:
                # audios.extend(audio_frames)
                audios.extend([xx for x in audio_chunks for xx in x])

            new_input_ids += [VID_START_ID]
            if targets is not None:
                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            for image_chunk_frames, audio_chunk_frames, second_chunk_frames in zip(
                image_chunks, audio_chunks, second_chunks
            ):
                for image_chunk_frame, second_chunk_frame in zip(image_chunk_frames, second_chunk_frames):
                    # add timestamp
                    timestamp = time.strftime("%H:%M:%S", time.gmtime(round(second_chunk_frame)))
                    _input_id = tokenizer(timestamp, add_special_tokens=False).input_ids
                    _target = [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(_input_id)
                    new_input_ids += _input_id
                    if targets is not None:
                        new_targets += _target

                    new_input_ids += [IMG_TAG_ID]
                    if targets is not None:
                        new_targets += [IMG_TAG_ID]

                for audio_chunk_frame in audio_chunk_frames:
                    new_input_ids += [AUD_TAG_ID]
                    if targets is not None:
                        new_targets += [AUD_TAG_ID]

            new_input_ids += [VID_END_ID]
            if targets is not None:
                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            video_grid_thw.extend(_video_grid_thw)
            second_per_grids.extend(_second_per_grids)

            st = vid_pos + 1

        new_input_ids += input_ids[st:]
        if targets is not None:
            new_targets += targets[st:]

        input_ids = new_input_ids
        if targets is not None:
            targets = new_targets

        if targets is not None:
            (
                input_ids,
                images,
                image_indices,
                image_grid_thw,
                targets,
            ) = self.image_processor.add_image_input_discrete_and_contiguous(
                input_ids,
                images,
                tokenizer,
                image_token_length=image_token_length,
                use_tile=False,
                targets=targets,
                is_pretrain=is_pretrain,
            )
        else:
            (
                input_ids,
                images,
                image_indices,
                image_grid_thw,
            ) = self.image_processor.add_image_input_discrete_and_contiguous(
                input_ids,
                images,
                tokenizer,
                image_token_length=image_token_length,
                use_tile=False,
            )

        if audio_frames is not None:
            if video_audio_chunk_size is None:
                video_audio_chunk_size = max(max([len(audio) for audio in audios]), 400)
            audios = [
                (
                    audio
                    if len(audio) == video_audio_chunk_size
                    else torch.cat([audio, torch.zeros(video_audio_chunk_size - len(audio))], dim=0),
                    self.sample_rate,
                )
                for audio in audios
            ]
            # print(f"{[x[0].size() for x in audios]=}")

            if targets is not None:
                (
                    input_ids,
                    audios,
                    audio_indices,
                    targets,
                ) = self.audio_processor.add_audio_input_discrete_and_contiguous(
                    input_ids, audios, tokenizer, targets=targets, is_pretrain=is_pretrain
                )
            else:
                (
                    input_ids,
                    audios,
                    audio_indices,
                ) = self.audio_processor.add_audio_input_discrete_and_contiguous(input_ids, audios, tokenizer)

        video_grid_thw = torch.tensor(video_grid_thw, dtype=torch.long)
        second_per_grids = torch.tensor(second_per_grids, dtype=torch.long)

        if targets is not None:
            return (
                input_ids,
                images,
                image_indices,
                audios,
                audio_indices,
                video_grid_thw,
                second_per_grids,
                targets,
            )

        return (
            input_ids,
            images,
            image_indices,
            audios,
            audio_indices,
            video_grid_thw,
            second_per_grids,
        )

        images = torch.cat(images, dim=0)
        image_indices = torch.cat(image_indices, dim=1)

        image_indices = image_indices.contiguous().to(torch.cuda.current_device())
        if True:
            images = torch.tensor(images, dtype=torch.bfloat16).contiguous().to(torch.cuda.current_device())

        else:
            images = torch.tensor(images, dtype=torch.float16).contiguous().to(torch.cuda.current_device())

        if len(audios) == 0:
            audios = None
            audio_indices = None

        return (
            input_ids,
            images,
            image_indices,
            audios,
            audio_indices,
            video_grid_thw,
            second_per_grids,
        )

    def add_video_input_discrete_or_contiguous(
        self,
        input_ids,
        video_paths,
        tokenizer,
        targets=None,
        discrete_video_idxs=[],
        contiguous_video_idxs=[],
        is_pretrain=False,
        max_num_frames=4096,
        max_fps=1,
        use_audio_in_video=True,
        use_vision_in_video=True,
        video_audio_chunk_min_second=2,
        video_audio_chunk_max_second=30,
        **kwargs,
    ):
        GLOBAL_TOKEN = get_token()

        IMG_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.IMG_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        IMG_START_ID = tokenizer(GLOBAL_TOKEN.IMG_START_TOKEN, add_special_tokens=False).input_ids
        IMG_END_ID = tokenizer(GLOBAL_TOKEN.IMG_END_TOKEN, add_special_tokens=False).input_ids

        AUD_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.AUD_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        AUD_START_ID = tokenizer(GLOBAL_TOKEN.AUD_START_TOKEN, add_special_tokens=False).input_ids
        AUD_END_ID = tokenizer(GLOBAL_TOKEN.AUD_END_TOKEN, add_special_tokens=False).input_ids

        VID_CONTEXT_ID = tokenizer(GLOBAL_TOKEN.VID_CONTEXT_TOKEN, add_special_tokens=False).input_ids
        VID_START_ID = tokenizer(GLOBAL_TOKEN.VID_START_TOKEN, add_special_tokens=False).input_ids
        VID_END_ID = tokenizer(GLOBAL_TOKEN.VID_END_TOKEN, add_special_tokens=False).input_ids

        IMG_TAG_ID = tokenizer(GLOBAL_TOKEN.IMG_TAG_TOKEN, add_special_tokens=False).input_ids
        AUD_TAG_ID = tokenizer(GLOBAL_TOKEN.AUD_TAG_TOKEN, add_special_tokens=False).input_ids
        VID_TAG_ID = tokenizer(GLOBAL_TOKEN.VID_TAG_TOKEN, add_special_tokens=False).input_ids

        assert len(IMG_CONTEXT_ID) == 1
        assert len(IMG_START_ID) == 1
        assert len(IMG_END_ID) == 1

        assert len(AUD_CONTEXT_ID) == 1
        assert len(AUD_START_ID) == 1
        assert len(AUD_END_ID) == 1

        assert len(VID_CONTEXT_ID) == 1
        assert len(VID_START_ID) == 1
        assert len(VID_END_ID) == 1

        IMG_CONTEXT_ID = IMG_CONTEXT_ID[0]
        IMG_START_ID = IMG_START_ID[0]
        IMG_END_ID = IMG_END_ID[0]

        AUD_CONTEXT_ID = AUD_CONTEXT_ID[0]
        AUD_START_ID = AUD_START_ID[0]
        AUD_END_ID = AUD_END_ID[0]

        VID_CONTEXT_ID = VID_CONTEXT_ID[0]
        VID_START_ID = VID_START_ID[0]
        VID_END_ID = VID_END_ID[0]

        IMG_TAG_ID = IMG_TAG_ID[0]
        AUD_TAG_ID = AUD_TAG_ID[0]
        VID_TAG_ID = VID_TAG_ID[0]

        nl_tokens = tokenizer("\n", add_special_tokens=False).input_ids

        vid_positions = [i for i, x in enumerate(input_ids) if x == VID_TAG_ID]
        assert len(vid_positions) == len(video_paths), video_paths

        if not discrete_video_idxs and not contiguous_video_idxs:
            contiguous_video_idxs = list(range(len(video_paths)))

        images = []
        image_indices = []
        audios = []
        audio_indices = []
        video_grid_thw = []
        second_per_grids = []

        new_input_ids = []
        new_targets = []
        st = 0
        for vid_idx, vid_pos in enumerate(vid_positions):
            (
                image_frames,
                audio_frames,
                audio_token_length_func,
                _video_grid_thw,
                _second_per_grids,
                second_frames,
                duration_seconds,
            ) = self.process_video(video_paths[vid_idx], max_num_frames, max_fps)

            if audio_frames is not None:
                # print(f"{len(image_frames)=} {len(audio_frames)=}")
                # print(f"{[x.size() for x in image_frames]=}")
                # print(f"{[x.size() for x in audio_frames]=}")

                num_frames = min(len(image_frames), len(audio_frames))
                image_frames = image_frames[:num_frames]
                audio_frames = audio_frames[:num_frames]

            new_input_ids += input_ids[st:vid_pos]
            if targets is not None:
                new_targets += targets[st:vid_pos]

            if audio_frames is not None:
                second_per_audio = 1.0 * duration_seconds / sum([len(x) for x in audio_frames])

                image_chunks = []
                image_second_chunks = []
                audio_chunks = []
                audio_second_chunks = []

                image_chunk = []
                image_second_chunk = []
                audio_chunk = []
                audio_second_chunk = []
                for image_frame, audio_frame, second_frame in zip(image_frames, audio_frames, second_frames):
                    audio_second = len(audio_frame) * second_per_audio
                    audio_chunk_second = sum([len(x) * second_per_audio for x in audio_chunk])

                    if audio_second + audio_chunk_second < video_audio_chunk_min_second:
                        image_chunk.append(image_frame)
                        image_second_chunk.append(second_frame)

                        audio_chunk.append(audio_frame)
                        audio_second_chunk.append(second_frame)

                    elif audio_second + audio_chunk_second <= video_audio_chunk_max_second:
                        image_chunk.append(image_frame)
                        image_second_chunk.append(second_frame)

                        audio_chunk.append(audio_frame)
                        audio_second_chunk.append(second_frame)

                        image_chunks.append(image_chunk)
                        image_second_chunks.append(image_second_chunk)

                        audio_chunk = [torch.cat(audio_chunk, dim=0)]
                        audio_second_chunk = [audio_second_chunk[0]]
                        audio_chunks.append(audio_chunk)
                        audio_second_chunks.append(audio_second_chunk)

                        image_chunk = []
                        image_second_chunk = []

                        audio_chunk = []
                        audio_second_chunk = []

                    else:
                        assert audio_chunk_second == 0

                        image_chunk.append(image_frame)
                        image_second_chunk.append(second_frame)

                        audio_chunk_size = int(video_audio_chunk_max_second / second_per_audio)
                        audio_chunk = torch.split(audio_frame, audio_chunk_size)
                        cur_second = second_frame
                        for x in audio_chunk:
                            audio_second_chunk.append(cur_second)
                            cur_second += len(x) * second_per_audio

                        image_chunks.append(image_chunk)
                        image_second_chunks.append(image_second_chunk)

                        audio_chunks.append(audio_chunk)
                        audio_second_chunks.append(audio_second_chunk)

                        image_chunk = []
                        image_second_chunk = []

                        audio_chunk = []
                        audio_second_chunk = []

                if len(image_chunk) > 0:
                    image_chunks.append(image_chunk)
                    image_second_chunks.append(image_second_chunk)

                    audio_chunk = [torch.cat(audio_chunk, dim=0)]
                    audio_second_chunk = [audio_second_chunk[0]]
                    audio_chunks.append(audio_chunk)
                    audio_second_chunks.append(audio_second_chunk)

            else:
                image_chunks = [image_frames]
                image_second_chunks = [second_frames]
                audio_chunks = [[]]
                audio_second_chunks = [[]]

            assert len(image_frames) == sum([len(x) for x in image_chunks])
            # assert len(audio_frames) == sum([len(x) for x in audio_chunks])

            if use_vision_in_video:
                if self.image_processor.resolution_type == "native":
                    images.append(
                        torch.cat(
                            [
                                self.image_processor.convert_image_to_patches_with_pixel_shuffle(x)
                                for x in image_frames
                            ],
                            dim=0,
                        )
                    )

                else:
                    images.append(image_frames)

            if use_audio_in_video and audio_frames is not None:
                # audios.extend(audio_frames)
                audios.extend([xx for x in audio_chunks for xx in x])

            new_input_ids += [VID_START_ID]
            if targets is not None:
                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            timestamp_format = "HHMMSS"

            for (
                image_chunk_frames,
                image_second_chunk_frames,
                audio_chunk_frames,
                audio_second_chunk_frames,
            ) in zip(
                image_chunks,
                image_second_chunks,
                audio_chunks,
                audio_second_chunks,
            ):
                if not use_vision_in_video:
                    image_chunk_frames = []
                    image_second_chunk_frames = []
                if not use_audio_in_video:
                    audio_chunk_frames = []
                    audio_second_chunk_frames = []

                for image_chunk_frame, image_second_chunk_frame in zip(image_chunk_frames, image_second_chunk_frames):
                    # add timestamp
                    if timestamp_format == "HHMMSS":
                        timestamp = time.strftime("%H:%M:%S", time.gmtime(round(image_second_chunk_frame)))
                    else:
                        timestamp = f"{image_second_chunk_frame:.2f}"
                    _input_id = tokenizer(timestamp, add_special_tokens=False).input_ids
                    new_input_ids += _input_id
                    if targets is not None:
                        if is_pretrain:
                            new_targets += _input_id
                        else:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(_input_id)

                    if vid_idx in contiguous_video_idxs:
                        new_input_ids += [IMG_START_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [IMG_START_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                        if self.image_processor.resolution_type == "native":
                            resolution = (
                                f"{_video_grid_thw[0][1] * self.patch_size}*{_video_grid_thw[0][2] * self.patch_size}"
                            )
                            _input_id = tokenizer(resolution, add_special_tokens=False).input_ids
                            new_input_ids += _input_id
                            if targets is not None:
                                if is_pretrain:
                                    # new_targets += _input_id
                                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(_input_id)
                                else:
                                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(_input_id)

                            for _ in range(_video_grid_thw[0][0] * _video_grid_thw[0][1] // self.spatial_merge_size):
                                image_token_length = _video_grid_thw[0][2] // self.spatial_merge_size
                                image_indice_b = torch.zeros(
                                    1, image_token_length, dtype=torch.int64
                                )  # This will change in collate_fn
                                image_indice_s = (
                                    torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                                    .unsqueeze(0)
                                    .repeat(1, 1)
                                )
                                image_indice_b_s = torch.stack(
                                    [image_indice_b, image_indice_s], dim=0
                                )  # 2, num_image, image_length
                                image_indices.append(image_indice_b_s.view(2, -1))

                                new_input_ids += [IMG_CONTEXT_ID] * image_token_length
                                if targets is not None:
                                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                                new_input_ids += nl_tokens
                                if targets is not None:
                                    if is_pretrain:
                                        new_targets += nl_tokens
                                    else:
                                        new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(nl_tokens)

                        else:
                            image_token_length = (
                                _video_grid_thw[0][0]
                                * _video_grid_thw[0][1]
                                * _video_grid_thw[0][2]
                                // self.spatial_merge_size
                                // self.spatial_merge_size
                            )
                            image_indice_b = torch.zeros(
                                1, image_token_length, dtype=torch.int64
                            )  # This will change in collate_fn
                            image_indice_s = (
                                torch.arange(len(new_input_ids), len(new_input_ids) + image_token_length)
                                .unsqueeze(0)
                                .repeat(1, 1)
                            )
                            image_indice_b_s = torch.stack(
                                [image_indice_b, image_indice_s], dim=0
                            )  # 2, num_image, image_length
                            image_indices.append(image_indice_b_s)

                            new_input_ids += [IMG_CONTEXT_ID] * image_token_length
                            if targets is not None:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * image_token_length

                        new_input_ids += [IMG_END_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [IMG_END_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                    if vid_idx in discrete_video_idxs:
                        raise NotImplementedError

                for audio_chunk_frame, audio_second_chunk_frame in zip(audio_chunk_frames, audio_second_chunk_frames):
                    # add timestamp
                    if timestamp_format == "HHMMSS":
                        timestamp = time.strftime("%H:%M:%S", time.gmtime(round(audio_second_chunk_frame)))
                    else:
                        timestamp = f"{audio_second_chunk_frame:.2f}"
                    _input_id = tokenizer(timestamp, add_special_tokens=False).input_ids
                    new_input_ids += _input_id
                    if targets is not None:
                        if is_pretrain:
                            new_targets += _input_id
                        else:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * len(_input_id)

                    if vid_idx in contiguous_video_idxs:
                        new_input_ids += [AUD_START_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [AUD_START_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                        # audio_token_length = audio_chunk_frame.size(0)
                        # audio_token_length = audio_token_length_func(audio_chunk_frame.size(0))
                        audio_token_length = audio_token_length_func(audio_chunk_frame)
                        audio_indice_b = torch.zeros(
                            1, audio_token_length, dtype=torch.int64
                        )  # This will change in collate_fn
                        audio_indice_s = (
                            torch.arange(len(new_input_ids), len(new_input_ids) + audio_token_length)
                            .unsqueeze(0)
                            .repeat(1, 1)
                        )
                        audio_indice_b_s = torch.stack(
                            [audio_indice_b, audio_indice_s], dim=0
                        )  # 2, num_audio, audio_length
                        audio_indices.append(audio_indice_b_s)

                        new_input_ids += [AUD_CONTEXT_ID] * audio_token_length
                        if targets is not None:
                            new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID] * audio_token_length

                        new_input_ids += [AUD_END_ID]
                        if targets is not None:
                            if is_pretrain:
                                new_targets += [AUD_END_ID]
                            else:
                                new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

                    if vid_idx in discrete_video_idxs:
                        raise NotImplementedError

            new_input_ids += [VID_END_ID]
            if targets is not None:
                if is_pretrain:
                    new_targets += [VID_END_ID]
                else:
                    new_targets += [GLOBAL_TOKEN.IGNORE_TOKEN_ID]

            video_grid_thw.extend(_video_grid_thw)
            second_per_grids.extend(_second_per_grids)

            st = vid_pos + 1

        new_input_ids += input_ids[st:]
        if targets is not None:
            new_targets += targets[st:]

        input_ids = new_input_ids
        if targets is not None:
            targets = new_targets

        video_grid_thw = torch.tensor(video_grid_thw, dtype=torch.long)
        second_per_grids = torch.tensor(second_per_grids, dtype=torch.long)

        if targets is not None:
            return (
                input_ids,
                images,
                image_indices,
                audios,
                audio_indices,
                video_grid_thw,
                second_per_grids,
                targets,
            )

        if len(images) == 0:
            images = None
            image_indices = None

        else:
            images = torch.cat(images, dim=0)
            image_indices = torch.cat(image_indices, dim=1)

            image_indices = image_indices.contiguous().to(torch.cuda.current_device())
            if True:
                images = torch.tensor(images, dtype=torch.bfloat16).contiguous().to(torch.cuda.current_device())

            else:
                images = torch.tensor(images, dtype=torch.float16).contiguous().to(torch.cuda.current_device())

        if len(audios) == 0:
            audios = None
            audio_indices = None

        return (
            input_ids,
            images,
            image_indices,
            audios,
            audio_indices,
            video_grid_thw,
            second_per_grids,
        )


__all__ = ["YoutuVITAVideoProcessor"]
