#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/mamba3_vita/modular_mamba3_vita.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_mamba3_vita.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

from ...configuration_utils import PreTrainedConfig


class Mamba3VITAAudioConfig(PreTrainedConfig):
    r"""
    Mamba3VITAAudioConfig
    """

    model_type = "mamba3_vita_audio"
    base_config_key = "audio_config"

    def __init__(
        self,
        hidden_size=512,
        temporal_merge_size=1,
        out_hidden_size=4608,
        merger_hidden_size=4608,
        downsample_hidden_size=512,
        num_mel_bins=128,
        n_window=50,
        n_window_infer=800,
        conv_chunksize=500,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.hidden_size = hidden_size
        self.temporal_merge_size = temporal_merge_size
        self.out_hidden_size = out_hidden_size
        self.merger_hidden_size = merger_hidden_size

        self.downsample_hidden_size = downsample_hidden_size
        self.num_mel_bins = num_mel_bins
        self.n_window = n_window
        self.n_window_infer = n_window_infer
        self.conv_chunksize = conv_chunksize
        self.num_hidden_layers = 0


class Mamba3VITAVisionConfig(PreTrainedConfig):
    r"""
    Mamba3VITAVisionConfig
    """

    model_type = "mamba3_vita_vision"
    base_config_key = "vision_config"

    def __init__(
        self,
        hidden_size=1024,
        d_state=128,
        expand=2,
        headdim=64,
        is_mimo=False,
        mimo_rank=4,
        chunk_size=64,
        is_outproj_norm=False,
        intermediate_size=4096,
        num_hidden_layers=12,
        num_channels=3,
        num_patches=256,
        patch_size=16,
        hidden_act="gelu_pytorch_tanh",
        layer_norm_eps=1e-6,
        attention_dropout=0.0,
        spatial_merge_size=2,
        out_hidden_size=4608,
        merger_hidden_size=4608,
        layer_type_list=None,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.hidden_size = hidden_size
        self.d_model = hidden_size
        self.d_state = d_state
        self.expand = expand
        self.headdim = headdim
        self.is_mimo = is_mimo
        self.mimo_rank = mimo_rank
        self.chunk_size = chunk_size
        self.is_outproj_norm = is_outproj_norm

        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_channels = num_channels
        self.num_patches = num_patches
        self.patch_size = patch_size
        self.hidden_act = hidden_act
        self.layer_norm_eps = layer_norm_eps
        self.attention_dropout = attention_dropout
        self.spatial_merge_size = spatial_merge_size
        self.out_hidden_size = out_hidden_size
        self.merger_hidden_size = merger_hidden_size

        self.layer_type_list = layer_type_list


class Mamba3VITATextConfig(PreTrainedConfig):
    r"""
    Mamba3VITATextConfig
    """

    model_type = "mamba3_vita_text"
    base_config_key = "text_config"
    keys_to_ignore_at_inference = ["past_key_values"]

    def __init__(
        self,
        vocab_size: int | None = 151936,
        hidden_size=1024,
        d_state=128,
        expand=2,
        headdim=64,
        is_mimo=False,
        mimo_rank=4,
        chunk_size=64,
        is_outproj_norm=False,
        intermediate_size=4096,
        num_hidden_layers=24,
        hidden_act: str | None = "silu",
        max_position_embeddings: int | None = 32768,
        initializer_range: float | None = 0.02,
        rms_norm_eps: float | None = 1e-6,
        use_cache: bool | None = True,
        tie_word_embeddings: bool | None = False,
        attention_dropout: float | None = 0.0,
        pad_token_id: int | None = None,
        bos_token_id: int | None = None,
        eos_token_id: int | None = None,
        layer_type_list=None,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.vocab_size = vocab_size
        self.max_position_embeddings = max_position_embeddings

        self.hidden_size = hidden_size
        self.d_model = hidden_size
        self.d_state = d_state
        self.expand = expand
        self.headdim = headdim
        self.is_mimo = is_mimo
        self.mimo_rank = mimo_rank
        self.chunk_size = chunk_size
        self.is_outproj_norm = is_outproj_norm

        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.hidden_act = hidden_act
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.attention_dropout = attention_dropout

        self.layer_type_list = layer_type_list

        self.pad_token_id = pad_token_id
        self.bos_token_id = bos_token_id
        self.eos_token_id = eos_token_id
        self.tie_word_embeddings = tie_word_embeddings


class Mamba3VITAConfig(PreTrainedConfig):
    r"""
    Mamba3VITAConfig
    """

    model_type = "mamba3_vita"
    sub_configs = {
        "audio_config": Mamba3VITAAudioConfig,
        "vision_config": Mamba3VITAVisionConfig,
        "text_config": Mamba3VITATextConfig,
    }
    keys_to_ignore_at_inference = ["past_key_values"]

    def __init__(
        self,
        audio_config=None,
        text_config=None,
        vision_config=None,
        # image_token_id=133375,
        # video_token_id=133379,
        # audio_token_id=133383,
        # image_pad_token_id=133376,
        # audio_pad_token_id=133384,
        # vision_start_token_id=133377,
        # vision_end_token_id=133378,
        tie_word_embeddings=False,
        **kwargs,
    ):
        if isinstance(audio_config, dict):
            self.audio_config = self.sub_configs["audio_config"](**audio_config)
        elif audio_config is None:
            self.audio_config = self.sub_configs["audio_config"]()

        if isinstance(vision_config, dict):
            self.vision_config = self.sub_configs["vision_config"](**vision_config)
        elif vision_config is None:
            self.vision_config = self.sub_configs["vision_config"]()

        if isinstance(text_config, dict):
            self.text_config = self.sub_configs["text_config"](**text_config)
        elif text_config is None:
            self.text_config = self.sub_configs["text_config"]()

        # self.image_token_id = image_token_id
        # self.video_token_id = video_token_id
        # self.audio_token_id = audio_token_id
        # self.image_pad_token_id = image_pad_token_id
        # self.audio_pad_token_id = audio_pad_token_id
        # self.vision_start_token_id = vision_start_token_id
        # self.vision_end_token_id = vision_end_token_id

        self.tie_word_embeddings = tie_word_embeddings
        super().__init__(**kwargs)


__all__ = ["Mamba3VITAConfig"]
