#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/mamba3_vita/modular_mamba3_vita.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_mamba3_vita.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

from collections.abc import Callable
from dataclasses import dataclass, fields
from typing import Optional

import torch
from torch import nn

from ... import initialization as init
from ...activations import ACT2FN
from ...cache_utils import Cache, DynamicCache
from ...generation import GenerationMixin
from ...integrations import use_kernel_forward_from_hub
from ...modeling_flash_attention_utils import FlashAttentionKwargs
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import (
    BaseModelOutput,
    BaseModelOutputWithPast,
    BaseModelOutputWithPooling,
    CausalLMOutputWithPast,
)
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from ...modeling_utils import PreTrainedModel
from ...processing_utils import AudioKwargs, Unpack
from ...trainer_pt_utils import LabelSmoother
from ...utils import TransformersKwargs, auto_docstring, logging
from ...utils.generic import check_model_inputs, maybe_autocast
from ...utils.import_utils import is_mamba_ssm_available
from .configuration_mamba3_vita import (
    Mamba3VITAAudioConfig,
    Mamba3VITAConfig,
    Mamba3VITATextConfig,
    Mamba3VITAVisionConfig,
)


if is_mamba_ssm_available():
    from mamba_ssm import Mamba3

logger = logging.get_logger(__name__)


def _get_feat_extract_output_lengths(input_lengths):
    """
    Computes the output length of the convolutional layers and the output length of the audio encoder
    """

    input_lengths_leave = input_lengths % 100
    feat_lengths = (input_lengths_leave - 1) // 2 + 1
    output_lengths = ((feat_lengths - 1) // 2 + 1 - 1) // 2 + 1 + (input_lengths // 100) * 13
    return output_lengths


class Mamba3VITACNNAudioEmbeddings(nn.Module):
    def __init__(self, config: Mamba3VITAAudioConfig):
        super().__init__()

        self.config = config

        self.n_window = config.n_window
        self.n_window_infer = self.config.n_window_infer
        self.conv_chunksize = self.config.conv_chunksize

        self.conv2d1 = nn.Conv2d(1, config.downsample_hidden_size, 3, 2, padding=1)
        self.conv2d2 = nn.Conv2d(config.downsample_hidden_size, config.downsample_hidden_size, 3, 2, padding=1)
        self.conv2d3 = nn.Conv2d(config.downsample_hidden_size, config.downsample_hidden_size, 3, 2, padding=1)

    def forward(
        self,
        input_features,
        feature_lens=None,
    ):
        input_features = input_features.to(self.conv2d1.weight.device)
        input_features = input_features.to(self.conv2d1.weight.dtype)

        aftercnn_lens = _get_feat_extract_output_lengths(feature_lens)
        chunk_num = torch.ceil(feature_lens / (self.n_window * 2)).long()

        chunk_lengths = torch.tensor(
            [self.n_window * 2] * chunk_num.sum(),
            dtype=torch.long,
            device=feature_lens.device,
        )
        tail_chunk_index = torch.nn.functional.pad(chunk_num, (1, 0), value=-1).cumsum(0)[1:]
        chunk_lengths[tail_chunk_index] = feature_lens % (self.n_window * 2)
        chunk_lengths[chunk_lengths == 0] = self.n_window * 2

        chunk_list = input_features.T.split(chunk_lengths.tolist(), dim=0)
        padded_feature = torch.nn.utils.rnn.pad_sequence(chunk_list, batch_first=True).transpose(1, 2)
        feature_lens_after_cnn = _get_feat_extract_output_lengths(chunk_lengths)
        padded_mask_after_cnn = torch.nn.utils.rnn.pad_sequence(
            [torch.ones(length, dtype=torch.bool, device=padded_feature.device) for length in feature_lens_after_cnn],
            batch_first=True,
        )
        padded_feature = padded_feature.unsqueeze(1)
        # Split to chunk to avoid OOM during convolution
        padded_embeds = []
        for chunk in padded_feature.split(self.conv_chunksize, dim=0):
            padded_embed = torch.nn.functional.gelu(self.conv2d1(chunk))
            padded_embed = torch.nn.functional.gelu(self.conv2d2(padded_embed))
            padded_embed = torch.nn.functional.gelu(self.conv2d3(padded_embed))
            padded_embeds.append(padded_embed)
        padded_embed = torch.cat(padded_embeds, dim=0)
        b, c, f, t = padded_embed.size()
        padded_embed = padded_embed.permute(0, 3, 1, 2).contiguous().view(b, t, c * f)

        hidden_states = padded_embed[padded_mask_after_cnn]

        return hidden_states, aftercnn_lens


class Mamba3VITACNNAudioEncoderLayer(nn.Module):
    def __init__(self, config: Mamba3VITAAudioConfig):
        super().__init__()

    def forward(
        self,
        hidden_states: torch.Tensor,
    ) -> tuple[torch.FloatTensor, torch.FloatTensor | None, tuple[torch.FloatTensor] | None]:
        return hidden_states


class Mamba3VITACNNAudioEncoder(nn.Module):
    def __init__(self, config: Mamba3VITAAudioConfig):
        super().__init__()
        self.config = config
        self.layers = nn.ModuleList(
            [Mamba3VITACNNAudioEncoderLayer(config) for idx in range(config.num_hidden_layers)]
        )
        self.gradient_checkpointing = True

    def forward(self, x):
        for idx, encoder_layer in enumerate(self.layers):
            x = encoder_layer(x)
        return x


class Mamba3VITACNNAudio(nn.Module):
    def __init__(self, config: Mamba3VITAAudioConfig):
        super().__init__()
        self.config = config

        self.embeddings = Mamba3VITACNNAudioEmbeddings(config)
        self.encoder = Mamba3VITACNNAudioEncoder(config)

    def forward(self, audios):

        audio_lengths = torch.as_tensor([len(x) for x in audios])
        # audios = torch.nn.utils.rnn.pad_sequence(audios, batch_first=True, padding_value=0.0)
        audios = torch.cat(audios, dim=0).transpose(1, 0)

        features, feature_lengths = self.embeddings(audios, audio_lengths)

        features = self.encoder(features)

        features = features.split(feature_lengths.tolist(), dim=0)
        features = torch.nn.utils.rnn.pad_sequence(features, batch_first=True, padding_value=0.0)

        return features, feature_lengths


def pad_and_reshape(A, M):
    B, S, D = A.shape

    # 1. Calculate required padding for the S dimension
    pad_size = (M - (S % M)) % M

    # 2. Pad (0, 0) for D, and (0, pad_size) for S
    # torch.nn.functional.pad expects padding for dimensions in reverse order:
    # (last_dim_front, last_dim_back, second_to_last_front, second_to_last_back, ...)
    if pad_size > 0:
        A = torch.nn.functional.pad(A, (0, 0, 0, pad_size))

    # Updated sequence length
    new_S = S + pad_size

    # 3. Reshape to (B, S // M, D * M)
    return A.view(B, new_S // M, M, D).flatten(2)


class Mamba3VITAAudioPatchMerger(nn.Module):
    def __init__(self, config: Mamba3VITAAudioConfig) -> None:
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size * (config.temporal_merge_size**1)
        self.norm = nn.RMSNorm(self.hidden_size)
        self.linear_fc1 = nn.Linear(self.hidden_size, config.merger_hidden_size, bias=False)
        self.act_fn = nn.GELU()
        self.linear_fc2 = nn.Linear(config.merger_hidden_size, config.out_hidden_size, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.config.temporal_merge_size > 1:
            x = pad_and_reshape(x, self.config.temporal_merge_size)
        x = self.norm(x.reshape(x.shape[0], -1, x.shape[-1]))
        x = self.linear_fc2(self.act_fn(self.linear_fc1(x)))
        return x


class Mamba3VITAVisionPatchMerger(nn.Module):
    def __init__(self, config: Mamba3VITAVisionConfig) -> None:
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size * (config.spatial_merge_size**2)
        self.norm = nn.RMSNorm(self.hidden_size)
        self.linear_fc1 = nn.Linear(self.hidden_size, config.merger_hidden_size, bias=False)
        self.act_fn = nn.GELU()
        self.linear_fc2 = nn.Linear(config.merger_hidden_size, config.out_hidden_size, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.norm(x.reshape(-1, self.hidden_size))
        x = self.linear_fc2(self.act_fn(self.linear_fc1(x)))
        return x


@use_kernel_forward_from_hub("RMSNorm")
class Mamba3VITATextRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps: float = 1e-6) -> None:
        """
        Mamba3VITATextRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class Mamba3VITATextRotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: Mamba3VITATextConfig, device=None):
        super().__init__()
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        self.rope_type = self.config.rope_parameters["rope_type"]
        rope_init_fn: Callable = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]
        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)

        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.register_buffer("original_inv_freq", inv_freq.clone(), persistent=False)

    @staticmethod
    def compute_default_rope_parameters(
        config: Mamba3VITATextConfig | None = None,
        device: Optional["torch.device"] = None,
        seq_len: int | None = None,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies according to the original RoPE implementation
        Args:
            config ([`~transformers.PreTrainedConfig`]):
                The model configuration.
            device (`torch.device`):
                The device to use for initialization of the inverse frequencies.
            seq_len (`int`, *optional*):
                The current sequence length. Unused for this type of RoPE.
        Returns:
            Tuple of (`torch.Tensor`, `float`), containing the inverse frequencies for the RoPE embeddings and the
            post-processing scaling factor applied to the computed cos/sin (unused in this type of RoPE).
        """
        base = config.rope_parameters["rope_theta"]
        dim = getattr(config, "head_dim", None) or config.hidden_size // config.num_attention_heads

        attention_factor = 1.0  # Unused in this type of RoPE

        # Compute the inverse frequencies
        inv_freq = 1.0 / (
            base ** (torch.arange(0, dim, 2, dtype=torch.int64).to(device=device, dtype=torch.float) / dim)
        )
        return inv_freq, attention_factor

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


class Mamba3VITATextMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


class Mamba3VITATextMixer(nn.Module):
    def __init__(self, config: Mamba3VITATextConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.is_causal = False

        self.d_model = config.d_model
        self.d_state = config.d_state
        self.expand = config.expand
        self.headdim = config.headdim

        self.is_mimo = config.is_mimo
        self.mimo_rank = config.mimo_rank
        self.chunk_size = config.chunk_size
        self.is_outproj_norm = config.is_outproj_norm

        self.d_inner = int(self.expand * self.d_model)

        self.layer = Mamba3(
            # This module uses roughly 6 * d_model^2 parameters
            d_model=self.d_model,  # Model dimension d_model
            d_state=self.d_state,  # SSM state size
            headdim=self.headdim,  # SSM headdim
            is_mimo=self.is_mimo,  # Use MIMO mode
            mimo_rank=self.mimo_rank,  # MIMO rank when is_mimo=True
            chunk_size=self.chunk_size,  # 64/mimo_rank if x is in bf16, else 32/mimo_rank.
            is_outproj_norm=self.is_outproj_norm,  # Additional post SSM norm
            dtype=torch.bfloat16,
        )

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: torch.Tensor | None,
        past_key_values: Cache | None = None,
        cache_position: torch.LongTensor | None = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor | None]:
        """Input shape: Batch x Time x Channel"""

        input_ndim = hidden_states.dim()
        if input_ndim == 3:
            pass
        elif input_ndim == 2:
            # [seq_len, hidden_size] -> [1, seq_len, hidden_size]
            hidden_states = hidden_states.unsqueeze(0)

        y = self.layer(hidden_states, cu_seqlens=kwargs.get("cu_seqlens"))

        if input_ndim == 3:
            pass
        elif input_ndim == 2:
            # [1, seq_len, hidden_size] -> [seq_len, hidden_size]
            y = y.squeeze(0)

        attn_weights = None

        return y, attn_weights


class Mamba3VITATextDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: Mamba3VITATextConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.layer_idx = layer_idx
        self.layer_type = config.layer_type_list[layer_idx]

        if self.layer_type == "M":
            self.input_layernorm = Mamba3VITATextRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
            self.mixer = Mamba3VITATextMixer(config=config, layer_idx=layer_idx)
        elif self.layer_type == "-":
            self.post_attention_layernorm = Mamba3VITATextRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
            self.mlp = Mamba3VITATextMLP(config)
        else:
            raise ValueError(f"Invalid layer type: {self.layer_type}")

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        use_cache: bool | None = False,
        cache_position: torch.LongTensor | None = None,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        """
        Args:
            hidden_states (`torch.FloatTensor`):
                Input to the layer of shape `(batch, seq_len, embed_dim)`.
            attention_mask (`torch.FloatTensor`):
                Attention mask of shape `(batch, 1, q_len, k_v_seq_len)` where padding elements are indicated by very large negative values.
            output_attentions (`bool`, *optional*, defaults to `False`):
                Whether or not to return the attentions tensors of all attention layers. See `attentions` under
                returned tensors for more detail.
        """
        if self.layer_type == "M":
            residual = hidden_states
            hidden_states = self.input_layernorm(hidden_states)
            hidden_states, _ = self.mixer(
                hidden_states=hidden_states,
                attention_mask=attention_mask,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )
            hidden_states = residual + hidden_states

        elif self.layer_type == "-":
            residual = hidden_states
            hidden_states = self.post_attention_layernorm(hidden_states)
            hidden_states = self.mlp(hidden_states)
            hidden_states = residual + hidden_states

        else:
            raise ValueError(f"Invalid layer type: {self.layer_type}")

        return hidden_states


class Mamba3VITAAudioPreTrainedModel(PreTrainedModel):
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    pass


class Mamba3VITAVisionPreTrainedModel(PreTrainedModel):
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    pass


class Mamba3VITAPreTrainedModel(PreTrainedModel):
    _supports_flash_attn_2 = True
    _supports_sdpa = True

    @torch.no_grad()
    def _init_weights(self, module):
        PreTrainedModel._init_weights(self, module)
        std = getattr(self.config, "initializer_range", 0.02)
        embed_std = getattr(self.config, "embedding_initializer_range", 2 * std)
        if isinstance(module, nn.Embedding):
            init.normal_(module.weight, mean=0.0, std=embed_std)
            if module.padding_idx is not None:
                init.zeros_(module.weight.data[module.padding_idx])


class Mamba3VITAAudioModel(Mamba3VITAAudioPreTrainedModel):
    config: Mamba3VITAAudioConfig

    def __init__(
        self,
        config: Mamba3VITAAudioConfig,
        *inputs,
        **kwargs,
    ):
        super().__init__(config, *inputs, **kwargs)

        self.model = Mamba3VITACNNAudio(config)
        self.merger = Mamba3VITAAudioPatchMerger(config)

    def forward(
        self,
        audios,
    ):
        encoder_out, encoder_out_lens = self.model(audios)
        encoder_out = self.merger(encoder_out)

        encoder_out_lens = -(-encoder_out_lens // self.config.temporal_merge_size)

        return encoder_out, encoder_out_lens


class Mamba3VITAVisionRotaryEmbedding(nn.Module):
    def __init__(self, dim: int, theta: float = 10000.0) -> None:
        super().__init__()
        # inv_freq = 1.0 / (theta ** (torch.arange(0, dim, 2, dtype=torch.float) / dim))
        # self.register_buffer("inv_freq", inv_freq, persistent=False)

        self.dim = dim
        self.theta = theta

    def forward(
        self,
        seqlen: torch.Tensor,
    ) -> torch.Tensor:
        # seq = torch.arange(seqlen, device=self.inv_freq.device, dtype=self.inv_freq.dtype)
        # freqs = torch.outer(seq, self.inv_freq)

        inv_freq = 1.0 / (
            self.theta ** (torch.arange(0, self.dim, 2, dtype=torch.float32, device=seqlen.device) / self.dim)
        )
        seq = torch.arange(seqlen, device=inv_freq.device, dtype=inv_freq.dtype)
        freqs = torch.outer(seq, inv_freq)
        return freqs


class Mamba3VITAVisionEmbeddings(nn.Module):
    def __init__(self, config: Mamba3VITAVisionConfig):
        super().__init__()
        self.config = config
        self.embed_dim = config.hidden_size
        self.patch_size = config.patch_size

        self.patch_embedding = nn.Linear(
            in_features=config.num_channels * self.patch_size * self.patch_size,
            out_features=self.embed_dim,
        )

    def forward(self, pixel_values: torch.FloatTensor, grid_thw: torch.LongTensor) -> torch.Tensor:
        """
        Args:
            pixel_values (`torch.FloatTensor`):
                Pixel values of shape (batch_size, max_num_tokens, num_channels * patch_size * patch_size)
            grid_thw (`List[Tuple[int, int]]`):
                Spatial shapes of shape (batch_size, 2) to resize the positional embeddings to
        """

        # Apply patch embeddings to already patchified pixel values
        target_dtype = self.patch_embedding.weight.dtype
        patch_embeds = self.patch_embedding(pixel_values.to(dtype=target_dtype))
        return patch_embeds


class Mamba3VITAVisionMixer(nn.Module):
    def __init__(self, config: Mamba3VITAVisionConfig):
        super().__init__()

        self.config = config
        self.is_causal = False

        self.d_model = config.d_model
        self.d_state = config.d_state
        self.expand = config.expand
        self.headdim = config.headdim

        self.is_mimo = config.is_mimo
        self.mimo_rank = config.mimo_rank
        self.chunk_size = config.chunk_size
        self.is_outproj_norm = config.is_outproj_norm

        self.d_inner = int(self.expand * self.d_model)

        self.layer = Mamba3(
            # This module uses roughly 6 * d_model^2 parameters
            d_model=self.d_model,  # Model dimension d_model
            d_state=self.d_state,  # SSM state size
            headdim=self.headdim,  # SSM headdim
            is_mimo=self.is_mimo,  # Use MIMO mode
            mimo_rank=self.mimo_rank,  # MIMO rank when is_mimo=True
            chunk_size=self.chunk_size,  # 64/mimo_rank if x is in bf16, else 32/mimo_rank.
            is_outproj_norm=self.is_outproj_norm,  # Additional post SSM norm
            dtype=torch.bfloat16,
        )

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        output_attentions: bool | None = False,
        cu_seqlens: torch.Tensor | None = None,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor | None]:
        """Input shape: Batch x Time x Channel"""

        y = self.layer(hidden_states.unsqueeze(0), cu_seqlens=cu_seqlens).squeeze(0)
        attn_weights = None

        return y, attn_weights


class Mamba3VITAVisionMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.activation_fn = ACT2FN[config.hidden_act]
        self.fc1 = nn.Linear(config.hidden_size, config.intermediate_size, bias=False)
        self.fc2 = nn.Linear(config.intermediate_size, config.hidden_size, bias=False)

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        hidden_states = self.fc1(hidden_states)
        hidden_states = self.activation_fn(hidden_states)
        hidden_states = self.fc2(hidden_states)
        return hidden_states


class Mamba3VITAVisionEncoderLayer(nn.Module):
    def __init__(self, config: Mamba3VITAVisionConfig, layer_idx: int):
        super().__init__()
        self.embed_dim = config.hidden_size

        self.layer_idx = layer_idx
        self.layer_type = config.layer_type_list[layer_idx]
        if self.layer_type == "M":
            # self.layer_norm1 = nn.LayerNorm(self.embed_dim, eps=config.layer_norm_eps)
            self.layer_norm1 = nn.RMSNorm(self.embed_dim, eps=config.layer_norm_eps)
            self.mixer = Mamba3VITAVisionMixer(config)
        elif self.layer_type == "-":
            # self.layer_norm2 = nn.LayerNorm(self.embed_dim, eps=config.layer_norm_eps)
            self.layer_norm2 = nn.RMSNorm(self.embed_dim, eps=config.layer_norm_eps)
            self.mlp = Mamba3VITAVisionMLP(config)
        else:
            raise ValueError(f"Invalid layer type: {self.layer_type}")

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        output_attentions: bool | None = False,
        cu_seqlens: torch.Tensor | None = None,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
    ) -> tuple[torch.FloatTensor]:
        """
        Args:
            hidden_states (`torch.FloatTensor`):
                Input to the layer of shape `(batch, seq_len, embed_dim)`.
            attention_mask (`torch.FloatTensor`):
                Attention mask of shape `(batch, 1, q_len, k_v_seq_len)` where padding elements are indicated by very large negative values.
            output_attentions (`bool`, *optional*, defaults to `False`):
                Whether or not to return the attentions tensors of all attention layers. See `attentions` under
                returned tensors for more detail.
        """
        if self.layer_type == "M":
            residual = hidden_states
            hidden_states = self.layer_norm1(hidden_states)
            hidden_states, attn_weights = self.mixer(
                hidden_states=hidden_states,
                attention_mask=attention_mask,
                output_attentions=output_attentions,
                cu_seqlens=cu_seqlens,
                position_embeddings=position_embeddings,
            )
            hidden_states = residual + hidden_states

        elif self.layer_type == "-":
            residual = hidden_states
            hidden_states = self.layer_norm2(hidden_states)
            hidden_states = self.mlp(hidden_states)
            hidden_states = residual + hidden_states

        else:
            raise ValueError(f"Invalid layer type: {self.layer_type}")

        outputs = (hidden_states,)

        if output_attentions:
            outputs += (attn_weights,)

        return outputs


class Mamba3VITAVisionEncoder(nn.Module):
    """
    Transformer encoder consisting of `config.num_hidden_layers` self attention layers. Each layer is a
    [`Mamba3VITAVisionEncoderLayer`].

    Args:
        config: Mamba3VITAVisionConfig
    """

    def __init__(self, config: Mamba3VITAVisionConfig):
        super().__init__()
        self.config = config
        self.layers = nn.ModuleList(
            [Mamba3VITAVisionEncoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.gradient_checkpointing = False

        self.spatial_merge_size = 2
        self.spatial_merge_unit = self.spatial_merge_size * self.spatial_merge_size
        self.patch_size = config.patch_size
        # self.window_size = self.patch_size * 2 * 8

        # self.rotary_pos_emb = Mamba3VITAVisionRotaryEmbedding(config.hidden_size // config.num_attention_heads // 2)

    def rot_pos_emb(self, grid_thw):
        pos_ids = []

        for t, h, w in grid_thw:
            hpos_ids = torch.arange(h).unsqueeze(1).expand(-1, w)

            hpos_ids = hpos_ids.reshape(
                h // self.spatial_merge_size,
                self.spatial_merge_size,
                w // self.spatial_merge_size,
                self.spatial_merge_size,
            )
            hpos_ids = hpos_ids.permute(0, 2, 1, 3)
            hpos_ids = hpos_ids.flatten()

            wpos_ids = torch.arange(w).unsqueeze(0).expand(h, -1)
            wpos_ids = wpos_ids.reshape(
                h // self.spatial_merge_size,
                self.spatial_merge_size,
                w // self.spatial_merge_size,
                self.spatial_merge_size,
            )
            wpos_ids = wpos_ids.permute(0, 2, 1, 3)
            wpos_ids = wpos_ids.flatten()
            pos_ids.append(torch.stack([hpos_ids, wpos_ids], dim=-1).repeat(t, 1))
        pos_ids = torch.cat(pos_ids, dim=0)
        max_grid_size = grid_thw[:, 1:].max()
        rotary_pos_emb_full = self.rotary_pos_emb(max_grid_size)
        rotary_pos_emb = rotary_pos_emb_full[pos_ids].flatten(1)
        return rotary_pos_emb

    # Ignore copy
    def forward(
        self,
        inputs_embeds,
        grid_thw,
        attention_mask: torch.Tensor | None = None,
        output_attentions: bool | None = None,
        output_hidden_states: bool | None = None,
    ) -> BaseModelOutput:
        r"""
        Args:
            inputs_embeds (`torch.FloatTensor` of shape `(batch_size, sequence_length, hidden_size)`):
                Optionally, instead of passing `input_ids` you can choose to directly pass an embedded representation.
                This is useful if you want more control over how to convert `input_ids` indices into associated vectors
                than the model's internal embedding lookup matrix.
            attention_mask (`torch.Tensor` of shape `(batch_size, sequence_length)`, *optional*):
                Mask to avoid performing attention on padding token indices. Mask values selected in `[0, 1]`:

                - 1 for tokens that are **not masked**,
                - 0 for tokens that are **masked**.

                [What are attention masks?](../glossary#attention-mask)
            output_attentions (`bool`, *optional*):
                Whether or not to return the attentions tensors of all attention layers. See `attentions` under
                returned tensors for more detail.
            output_hidden_states (`bool`, *optional*):
                Whether or not to return the hidden states of all layers. See `hidden_states` under returned tensors
                for more detail.
            return_dict (`bool`, *optional*):
                Whether or not to return a [`~utils.ModelOutput`] instead of a plain tuple.
        """
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )

        encoder_states = () if output_hidden_states else None
        all_attentions = () if output_attentions else None

        # rotary_pos_emb = self.rot_pos_emb(grid_thw)

        # emb = torch.cat((rotary_pos_emb, rotary_pos_emb), dim=-1)
        # position_embeddings = (emb.cos(), emb.sin())

        cu_seqlens = torch.repeat_interleave(grid_thw[:, 1] * grid_thw[:, 2], grid_thw[:, 0]).cumsum(
            dim=0,
            dtype=grid_thw.dtype if torch.jit.is_tracing() else torch.int32,
        )
        cu_seqlens = torch.nn.functional.pad(cu_seqlens, (1, 0), value=0)

        hidden_states = inputs_embeds
        for encoder_layer in self.layers:
            if output_hidden_states:
                encoder_states = encoder_states + (hidden_states,)
            if self.gradient_checkpointing and self.training:
                layer_outputs = self._gradient_checkpointing_func(
                    encoder_layer.__call__,
                    hidden_states,
                    attention_mask,
                    output_attentions,
                    cu_seqlens,
                    # position_embeddings,
                )
            else:
                layer_outputs = encoder_layer(
                    hidden_states,
                    attention_mask,
                    output_attentions=output_attentions,
                    cu_seqlens=cu_seqlens,
                    # position_embeddings=position_embeddings
                )

            hidden_states = layer_outputs[0]

            if output_attentions:
                all_attentions = all_attentions + (layer_outputs[1],)

        if output_hidden_states:
            encoder_states = encoder_states + (hidden_states,)

        return BaseModelOutput(
            last_hidden_state=hidden_states,
            hidden_states=encoder_states,
            attentions=all_attentions,
        )


class Mamba3VITAVisionModel(Mamba3VITAVisionPreTrainedModel):
    _input_embed_layer = "patch_embedding"
    config: Mamba3VITAVisionConfig

    def __init__(self, config, *inputs, **kwargs) -> None:
        super().__init__(config, *inputs, **kwargs)
        self.config = config
        embed_dim = config.hidden_size

        self.embeddings = Mamba3VITAVisionEmbeddings(config)
        self.encoder = Mamba3VITAVisionEncoder(config)

        self.merger = Mamba3VITAVisionPatchMerger(config)

    def forward(
        self,
        pixel_values: torch.FloatTensor,
        grid_thw: torch.LongTensor,
        attention_mask: torch.Tensor,
        output_attentions: bool | None = None,
        output_hidden_states: bool | None = None,
    ) -> BaseModelOutputWithPooling:
        r"""
        Returns:

        """
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )

        hidden_states = self.embeddings(pixel_values, grid_thw)

        if attention_mask is not None and not self._use_flash_attention_2:
            # [batch_size, seq_len] -> [batch_size, 1, tgt_seq_len, src_seq_len]
            encoder_attention_mask = _prepare_4d_attention_mask(attention_mask, hidden_states.dtype)
        else:
            encoder_attention_mask = attention_mask

        encoder_outputs: BaseModelOutput = self.encoder(
            inputs_embeds=hidden_states,
            grid_thw=grid_thw,
            attention_mask=encoder_attention_mask,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
        )

        last_hidden_state = encoder_outputs.last_hidden_state
        # last_hidden_state = self.post_layernorm(last_hidden_state)

        # pooler_output = self.head(last_hidden_state, attention_mask) if self.use_head else None
        pooler_output = None

        assert last_hidden_state.shape[0] == len(pixel_values)
        last_hidden_state = self.merger(last_hidden_state)

        return BaseModelOutputWithPooling(
            last_hidden_state=last_hidden_state,
            pooler_output=pooler_output,
            hidden_states=encoder_outputs.hidden_states,
            attentions=encoder_outputs.attentions,
        )


class Mamba3VITATextModel(Mamba3VITAPreTrainedModel):
    config: Mamba3VITATextConfig

    def __init__(self, config: Mamba3VITATextConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [Mamba3VITATextDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = Mamba3VITATextRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        # self.rotary_emb = Mamba3VITATextRotaryEmbedding(config=config)
        self.gradient_checkpointing = False
        # self.has_sliding_layers = "sliding_attention" in self.config.layer_types

        # Initialize weights and apply final processing
        self.post_init()

    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        use_cache: bool | None = None,
        cache_position: torch.LongTensor | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        # # It may already have been prepared by e.g. `generate`
        # if not isinstance(causal_mask_mapping := attention_mask, dict):
        #     # Prepare mask arguments
        #     mask_kwargs = {
        #         "config": self.config,
        #         "input_embeds": inputs_embeds,
        #         "attention_mask": attention_mask,
        #         "cache_position": cache_position,
        #         "past_key_values": past_key_values,
        #         "position_ids": position_ids,
        #     }
        #     # Create the masks
        #     causal_mask_mapping = {
        #         "full_attention": create_causal_mask(**mask_kwargs),
        #     }
        #     # The sliding window alternating layers are not always activated depending on the config
        #     if self.has_sliding_layers:
        #         causal_mask_mapping["sliding_attention"] = create_sliding_window_causal_mask(**mask_kwargs)

        hidden_states = inputs_embeds
        # position_embeddings = self.rotary_emb(hidden_states, position_ids)

        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            hidden_states = decoder_layer(
                hidden_states,
                # attention_mask=causal_mask_mapping[decoder_layer.attention_type],
                # position_embeddings=position_embeddings,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                **kwargs,
            )

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
        )


class Mamba3VITAModel(Mamba3VITAPreTrainedModel):
    def __init__(self, config: Mamba3VITAConfig):
        super().__init__(config)
        self.audio_model = Mamba3VITAAudioModel._from_config(config.audio_config)
        self.vision_model = Mamba3VITAVisionModel._from_config(config.vision_config)
        self.language_model = Mamba3VITATextModel._from_config(config.text_config)

    def get_input_embeddings(self):
        return self.language_model.embed_tokens

    def set_input_embeddings(self, value):
        self.language_model.embed_tokens = value

    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        images: torch.FloatTensor | None = None,
        image_indices: torch.LongTensor | None = None,
        image_grid_thw: torch.LongTensor | None = None,
        audios: torch.FloatTensor | None = None,
        audio_indices: torch.LongTensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        cache_position: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:

        if images is not None:
            device = self.get_input_embeddings().weight.data.device
            dtype = self.get_input_embeddings().weight.data.dtype
            images = images.to(dtype).to(device)
            image_grid_thw = image_grid_thw.to(device)
            # print(f"{input_ids.size()=}")
            # print(f"{image_indices.size()=}")
            # print(f"{image_grid_thw.size()=}")
            # print(f"{images.size()=}")

            if len(image_grid_thw) > 64:
                image_embeds = []
                image_grid_thw = torch.split(image_grid_thw, 64, dim=0)
                chunk_num = len(image_grid_thw)
                im_st = 0
                for chunk_idx in range(chunk_num):
                    _image_grid_thw = image_grid_thw[chunk_idx]
                    im_ed = (
                        im_st + (_image_grid_thw[:, 1] * _image_grid_thw[:, 2] * _image_grid_thw[:, 0]).sum().item()
                    )
                    _image_embeds = self.vision_model(
                        pixel_values=images[im_st:im_ed],
                        attention_mask=None,
                        grid_thw=image_grid_thw[chunk_idx],
                    ).last_hidden_state
                    image_embeds.append(_image_embeds)

                    im_st = im_ed
                image_embeds = torch.cat(image_embeds, dim=0)
            else:
                image_embeds = self.vision_model(
                    pixel_values=images,
                    attention_mask=None,
                    grid_thw=image_grid_thw,
                ).last_hidden_state
            # print(f"image_embeds {image_embeds.size()}")
            # assert image_embeds.shape[0] == len(images)
            fake_images = None

            # image_embeds = image_embeds[:, 1:, :]
            # image_embeds = self.vision_projection(image_embeds)

            # torch.set_printoptions(threshold=100_000)
            # print(f"{image_embeds.size()=}")

        elif self.training:
            device = self.get_input_embeddings().weight.data.device
            dtype = self.get_input_embeddings().weight.data.dtype
            # fake_images = torch.ones((1 * self.config.vision["image_size"] // self.config.vision["patch_size"] * self.config.vision["image_size"] // self.config.vision["patch_size"], 3 * self.config.vision["patch_size"] * self.config.vision["patch_size"]), dtype=dtype, device=device)
            # image_grid_thw = torch.tensor([[1, self.config.vision["image_size"] // self.config.vision["patch_size"], self.config.vision["image_size"] // self.config.vision["patch_size"]]], dtype=torch.int64, device=device)
            fake_images = torch.ones(
                (
                    1 * 512 // self.vision_config.patch_size * 512 // self.vision_config.patch_size,
                    3 * self.vision_config.patch_size * self.vision_config.patch_size,
                ),
                dtype=dtype,
                device=device,
            )
            image_grid_thw = torch.tensor(
                [[1, 512 // self.vision_config.patch_size, 512 // self.vision_config.patch_size]],
                dtype=torch.int64,
                device=device,
            )

            # print(f"{input_ids.size()=}")
            # print(f"{image_indices.size()=}")
            # print(f"{image_grid_thw.size()=}")
            # print(f"{fake_images.size()=}")

            image_embeds = self.vision_model(
                pixel_values=fake_images,
                attention_mask=None,
                grid_thw=image_grid_thw,
            ).last_hidden_state
            # image_embeds = image_embeds[:, 1:, :]
            # image_embeds = self.vision_projection(image_embeds)

            # torch.set_printoptions(threshold=100_000)
            # print(f"{image_embeds.size()=}")

        else:
            fake_images = None
            image_embeds = None

        if audios is not None:
            audio_embeds, audio_lengths = self.audio_model(audios)
            # if torch.distributed.get_rank() == 0:
            #     print(f"audio_embeds {audio_embeds.size()}")
            # assert audio_embeds.shape[0] == len(audios)
            fake_audios = None

            # audio_embeds = self.audio_projection(audio_embeds)

            # torch.set_printoptions(threshold=100_000)
            # if torch.distributed.get_rank() == 0:
            #     print(f"audio_embeds {audio_embeds.size()}")
            #     print(f"audio_embeds {audio_embeds.sum()}")
            #     print(f"audios {[x.size() for x in audios]}")
            #     print(f"audios {[x.sum() for x in audios]}")
            #     print(f"input_ids {input_ids.size()}")
            #     print(f"input_ids {input_ids.sum()}")
            #     # print(f"input_ids {input_ids}")
            #     print(f"audio_indices {[x.size() for x in audio_indices]}")
            #     print(f"audio_indices {[x.sum() for x in audio_indices]}")
            #     # print(f"audio_indices {audio_indices}")

        elif self.training:
            device = self.get_input_embeddings().weight.data.device
            dtype = self.get_input_embeddings().weight.data.dtype
            fake_audios = torch.ones((1, 1, 560), dtype=dtype, device=device)
            audio_embeds, audio_lengths = self.audio_model(fake_audios)
            # audio_embeds = self.audio_projection(audio_embeds)

        else:
            fake_audios = None
            audio_embeds = None

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds: torch.Tensor = self.language_model.embed_tokens(input_ids)
            input_ids = None

        if fake_images is not None:
            inputs_embeds = inputs_embeds + image_embeds.mean() * 0.0
        elif image_embeds is not None:
            inputs_embeds = inputs_embeds.clone()
            image_embeds = image_embeds.to(inputs_embeds.device)
            image_indices = image_indices.to(inputs_embeds.device)
            indices_b, indices_s = image_indices.unbind(dim=0)
            inputs_embeds[indices_b.view(-1), indices_s.view(-1)] = image_embeds.view(-1, image_embeds.shape[-1])
            # inputs_embeds = inputs_embeds + image_embeds.mean() * 0.0

        if fake_audios is not None:
            inputs_embeds = inputs_embeds + audio_embeds.mean() * 0.0
        elif audio_embeds is not None:
            inputs_embeds = inputs_embeds.clone()
            for audio_embeds_, audio_lengths_, audio_indices_ in zip(
                audio_embeds,
                audio_lengths,
                audio_indices,
            ):
                # print(f"{audio_embeds_.size()=} {audio_lengths_=} {audio_indices_.size()=}")
                audio_embeds_ = audio_embeds_[:audio_lengths_, ...]
                audio_embeds_ = audio_embeds_.to(inputs_embeds.device)
                indices_b, indices_s = audio_indices_.to(inputs_embeds.device).unbind(dim=0)
                inputs_embeds[indices_b.view(-1), indices_s.view(-1)] = audio_embeds_.view(-1, audio_embeds_.shape[-1])
            # inputs_embeds = inputs_embeds + audio_embeds.mean() * 0.0

        return self.language_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )


class Mamba3VITAForCausalLM(Mamba3VITAPreTrainedModel, GenerationMixin):
    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_gather_output"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config: Mamba3VITAConfig):
        super().__init__(config)
        self.model = Mamba3VITAModel(config)
        self.vocab_size = config.text_config.vocab_size
        self.lm_head = nn.Linear(config.text_config.hidden_size, config.text_config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        images: torch.FloatTensor | None = None,
        image_indices: torch.LongTensor | None = None,
        image_grid_thw: torch.LongTensor | None = None,
        audios: torch.FloatTensor | None = None,
        audio_indices: torch.LongTensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        cache_position: torch.LongTensor | None = None,
        logits_to_keep: int | torch.Tensor = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        r"""
        Example:

        ```python
        >>> from transformers import AutoTokenizer, Qwen3ForCausalLM

        >>> model = Qwen3ForCausalLM.from_pretrained("meta-Qwen3/Qwen3-2-7b-hf")
        >>> tokenizer = AutoTokenizer.from_pretrained("meta-Qwen3/Qwen3-2-7b-hf")

        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            images=images,
            image_indices=image_indices,
            image_grid_thw=image_grid_thw,
            audios=audios,
            audio_indices=audio_indices,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(
                logits=logits, labels=labels, vocab_size=self.config.text_config.vocab_size, **kwargs
            )

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )

    def prepare_inputs_for_generation(
        self,
        input_ids: torch.LongTensor,
        past_key_values: Cache | None = None,
        attention_mask: torch.LongTensor | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        cache_position: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        images: torch.FloatTensor | None = None,
        image_indices: torch.LongTensor | None = None,
        image_grid_thw: torch.LongTensor | None = None,
        audios: torch.FloatTensor | None = None,
        audio_indices: torch.LongTensor | None = None,
        is_first_iteration: bool | None = False,
        **kwargs,
    ):
        model_inputs = super().prepare_inputs_for_generation(
            input_ids,
            past_key_values=past_key_values,
            attention_mask=attention_mask,
            inputs_embeds=inputs_embeds,
            cache_position=cache_position,
            use_cache=use_cache,
            images=images,
            image_indices=image_indices,
            image_grid_thw=image_grid_thw,
            audios=audios,
            audio_indices=audio_indices,
            is_first_iteration=is_first_iteration,
            **kwargs,
        )

        if not is_first_iteration and use_cache:
            model_inputs["images"] = None
            model_inputs["audios"] = None

        return model_inputs


@dataclass
class DEFAULT_TOKEN:
    IMAGENET_DEFAULT_MEAN = [0.485, 0.456, 0.406]
    IMAGENET_DEFAULT_STD = [0.229, 0.224, 0.225]
    IMAGENET_STANDARD_MEAN = [0.5, 0.5, 0.5]
    IMAGENET_STANDARD_STD = [0.5, 0.5, 0.5]
    OPENAI_CLIP_MEAN = [0.48145466, 0.4578275, 0.40821073]
    OPENAI_CLIP_STD = [0.26862954, 0.26130258, 0.27577711]

    # Model Constants
    IGNORE_INDEX = -100
    IMAGE_TOKEN_INDEX = -200
    # DEFAULT_IMAGE_TOKEN = IMG_CONTEXT_TOKEN
    # DEFAULT_IMAGE_PATCH_TOKEN = PATCH_CONTEXT_TOKEN
    # DEFAULT_IM_START_TOKEN = IMG_START_TOKEN
    # DEFAULT_IM_END_TOKEN = IMG_END_TOKEN

    IGNORE_TOKEN_ID = LabelSmoother.ignore_index

    def __init__(self):

        for field in fields(self):
            logger.info(f"♾️ {field.name} {getattr(self, field.name)}")
            print(f"♾️ {field.name} {getattr(self, field.name)}")


class Mamba3_VITA_TOKEN(DEFAULT_TOKEN):
    IM_START = "<|begin_of_text|>"
    IM_END = "<|end_of_text|>"
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"

    IMG_TAG_TOKEN = "<|image|>"
    IMG_CONTEXT_TOKEN = "<|image_pad|>"
    IMG_START_TOKEN = "<|vision_start|>"
    IMG_END_TOKEN = "<|vision_end|>"

    VID_TAG_TOKEN = "<|video|>"
    VID_CONTEXT_TOKEN = "<|video_pad|>"
    VID_START_TOKEN = "<|video_start|>"
    VID_END_TOKEN = "<|video_end|>"

    AUD_TAG_TOKEN = "<|audio|>"
    AUD_CONTEXT_TOKEN = "<|audio_pad|>"
    AUD_START_TOKEN = "<|audio_start|>"
    AUD_END_TOKEN = "<|audio_end|>"

    THINK_START_TOKEN = "<think>"
    THINK_END_TOKEN = "</think>"
    CODE_START_TOKEN = "<code>"
    CODE_END_TOKEN = "</code>"
    ANSWER_START_TOKEN = "<answer>"
    ANSWER_END_TOKEN = "</answer>"

    TOOL_CALL_START_TOKEN = "<tool_call>"
    TOOL_CALL_END_TOKEN = "</tool_call>"
    TOOL_RESPONSE_START_TOKEN = "<tool_response>"
    TOOL_RESPONSE_END_TOKEN = "</tool_response>"

    ACTION_START_TOKEN = "<action>"
    ACTION_END_TOKEN = "</action>"
    OPERATION_START_TOKEN = "<operation>"
    OPERATION_END_TOKEN = "</operation>"
    CLICK_TOKEN = "<click>"
    MOVETO_TOKEN = "<moveTo>"
    SCROLL_TOKEN = "<scroll>"
    WRITE_TOKEN = "<write>"
    DRAGTO_TOKEN = "<dragTo>"
    KEYDOWN_TOKEN = "<keyDown>"
    KEYUP_TOKEN = "<keyUp>"

    POLY_START_TOKEN = "<poly>"
    POLY_END_TOKEN = "</poly>"
    INS_START_TOKEN = "<ins>"
    INS_END_TOKEN = "</ins>"
    CKPT_START_TOKEN = "<kpt>"
    CKPT_END_TOKEN = "</kpt>"
    BOX_START_TOKEN = "<box>"
    BOX_END_TOKEN = "</box>"
    REF_START_TOKEN = "<ref>"
    REF_END_TOKEN = "</ref>"
    FG_TOKEN = "<FG>"
    BG_TOKEN = "<BG>"
    OTHERS_TOKEN = "<OTHERS>"

    def __init__(self):
        logger.info(f"♾️ {self.__class__.__name__=}")
        print(f"♾️ {self.__class__.__name__=}")
        super().__init__()

        for i in range(2048):
            for axis in ["x", "y"]:
                setattr(self, f"{axis}_{i}_TOKEN", f"<{axis}_{i}>")

        for i in range(1, 1001):
            setattr(self, f"custom_{i}_TOKEN", f"<custom_{i}>")

    def get_special_tokens(self):
        return (
            [
                self.IM_START,
                self.IM_END,
                self.IMG_TAG_TOKEN,
                self.IMG_CONTEXT_TOKEN,
                self.IMG_START_TOKEN,
                self.IMG_END_TOKEN,
                self.VID_TAG_TOKEN,
                self.VID_CONTEXT_TOKEN,
                self.VID_START_TOKEN,
                self.VID_END_TOKEN,
                self.AUD_TAG_TOKEN,
                self.AUD_CONTEXT_TOKEN,
                self.AUD_START_TOKEN,
                self.AUD_END_TOKEN,
                self.THINK_START_TOKEN,
                self.THINK_END_TOKEN,
                self.CODE_START_TOKEN,
                self.CODE_END_TOKEN,
                self.ANSWER_START_TOKEN,
                self.ANSWER_END_TOKEN,
                self.TOOL_CALL_START_TOKEN,
                self.TOOL_CALL_END_TOKEN,
                self.TOOL_RESPONSE_START_TOKEN,
                self.TOOL_RESPONSE_END_TOKEN,
                self.ACTION_START_TOKEN,
                self.ACTION_END_TOKEN,
                self.OPERATION_START_TOKEN,
                self.OPERATION_END_TOKEN,
                self.CLICK_TOKEN,
                self.MOVETO_TOKEN,
                self.SCROLL_TOKEN,
                self.WRITE_TOKEN,
                self.DRAGTO_TOKEN,
                self.KEYDOWN_TOKEN,
                self.KEYUP_TOKEN,
                self.POLY_START_TOKEN,
                self.POLY_END_TOKEN,
                self.INS_START_TOKEN,
                self.INS_END_TOKEN,
                self.CKPT_START_TOKEN,
                self.CKPT_END_TOKEN,
                self.BOX_START_TOKEN,
                self.BOX_END_TOKEN,
                self.REF_START_TOKEN,
                self.REF_END_TOKEN,
                self.FG_TOKEN,
                self.BG_TOKEN,
                self.OTHERS_TOKEN,
            ]
            + [getattr(self, f"{axis}_{i}_TOKEN") for i in range(2048) for axis in ["x", "y"]]
            + [getattr(self, f"custom_{i}_TOKEN") for i in range(1, 1001)]
        )


class Mamba3VITAAudioKwargs(AudioKwargs, total=False):
    """ """

    discrete_audio_idxs: list
    contiguous_audio_idxs: list

    # temporal_merge_size: int

    # audio_tokenizer_type: str
    # audio_tokenizer_path: str


__all__ = ["Mamba3VITAPreTrainedModel", "Mamba3VITAModel", "Mamba3VITAForCausalLM"]
